
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'common.search': 'Search tasks, owners...',
    'common.filter': 'All Statuses',
    'common.add': 'Add',
    'common.delete': 'Delete',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.done': 'Done',
    'common.close': 'Close',
    'common.note': 'Note',
    'common.warn': 'Warn',
    'common.back': 'Back',
    'common.select': 'Select',
    'common.create': 'Create',
    'common.save_changes': 'Save Changes',
    'common.confirm': 'Confirm',
    // App
    'app.title': 'Gen-Project Manager',
    'app.desc': 'AI-Powered Project Management',
    'app.view.dashboard': 'Dashboard',
    'app.view.projects': 'Projects',
    'app.view.list': 'List',
    'app.view.board': 'Board',
    'app.view.gantt': 'Gantt',
    'app.view.calendar': 'Calendar',
    'app.view.meetings': 'Meetings',
    'app.view.wiki': 'Knowledge Base',
    'app.view.goals': 'Goals & Strategy',
    'app.view.files': 'File Hub',
    'app.view.finance': 'Finance',
    'app.view.issues': 'Issue Tracker',
    'app.view.risks': 'Risks',
    'app.export': 'Export CSV',
    'app.team': 'Team',
    'app.ai_generate': 'AI Generate',
    'app.new_phase': 'New Phase',
    'app.no_data': 'No data available.',
    'app.create_phase': 'Create Phase',
    'app.gen_ai': 'Generate with AI',
    'app.switch_lang': '中文',
    // Project Meta
    'project.back': 'Back to Projects',
    'project.name_label': 'Project Name',
    'project.desc_label': 'Description',
    'project.manager_label': 'Project Manager',
    'project.created': 'Created',
    'project.unnamed': 'Unnamed Project',
    'project.no_desc': 'No description provided.',
    'project.delete_confirm_title': 'Delete Project?',
    'project.delete_confirm_msg': 'This will permanently delete the project and all associated tasks, meetings, and documents.',
    'project.code': 'Code',
    'project.budget_total': 'Total Budget',
    'project.settings_title': 'Project Settings',
    // Dashboard
    'dash.total_tasks': 'Total Tasks',
    'dash.completion_rate': 'Completion Rate',
    'dash.pending_items': 'Pending Items',
    'dash.delayed': 'Delayed / Risk',
    'dash.team_workload': 'Team Workload',
    'dash.status_dist': 'Task Status Distribution',
    'dash.upcoming': 'Upcoming Deadlines',
    'dash.no_upcoming': 'No immediate deadlines.',
    'dash.recent_activity': 'Recent Activity',
    'dash.phase_progress': 'Phase Progress',
    // ProjectTable
    'table.phase_tasks': 'tasks',
    'table.add_task': 'Add Task',
    'table.task_name': 'Task Name',
    'table.description': 'Task Description',
    'table.deliverables': 'Deliverables',
    'table.wait_for': 'Wait: ',
    'table.status': 'Status',
    'table.priority': 'Priority',
    'table.schedule': 'Schedule',
    'table.assigned_to': 'Assigned To',
    'table.overdue': 'Overdue',
    'table.days': 'days',
    'table.set_duration': 'Set Duration',
    'table.start_date': 'Start Date',
    'table.end_date': 'End Date',
    'table.link_name': 'Name (e.g. Figma)',
    'table.link_url': 'URL (https://...)',
    'table.add_link': 'Add Link',
    'table.attachments': 'Attachments',
    'table.no_links': 'No links yet.',
    'table.wait_tasks': 'Wait for tasks:',
    'table.delete_task_confirm': 'Delete this task?',
    'table.serial_number': 'No.',
    // Status
    'status.Pending': 'Pending',
    'status.In Progress': 'In Progress',
    'status.Completed': 'Completed',
    'status.Delayed': 'Delayed',
    'status.All': 'All Statuses',
    // Priority
    'priority.Low': 'Low',
    'priority.Med': 'Med',
    'priority.High': 'High',
    // AI Generator
    'ai.title': 'AI Project Architect',
    'ai.subtitle': "Describe what you want to build, and I'll create a structured plan.",
    'ai.subtitle.settings': 'Configure your AI Provider',
    'ai.placeholder': 'e.g., Organize a Tech Conference ...',
    'ai.btn.generate': 'Generate Plan',
    'ai.btn.generating': 'Generating...',
    'ai.btn.import': 'Import to Project',
    'ai.preview': 'Preview Generated Plan',
    'ai.start_over': 'Start Over',
    'ai.settings': 'Settings',
    'ai.provider': 'AI Provider',
    'ai.api_key': 'API Key',
    'ai.model': 'Model Name',
    'ai.base_url': 'Base URL',
    'ai.cancel': 'Cancel',
    'ai.save_config': 'Save Configuration',
    'ai.thinking': 'Thinking...',
    'ai.phase': 'PHASE',
    'ai.target_project': 'Target Project',
    'ai.structure_type': 'Structure Type',
    'ai.structure.full': 'Full Project (Multiple Phases)',
    'ai.structure.single': 'Single Phase (Task List)',
    'ai.select_project': 'Select a Project...',
    // Kanban
    'kanban.move_to': 'Move to:',
    'kanban.drop': 'Drop items here',
    'kanban.no_phases': 'No existing phases',
    // Team
    'team.title': 'Team Directory',
    'team.subtitle': 'Manage your team, view workloads, and track assignments.',
    'team.add_new': 'Add Member',
    'team.current': 'Current Members',
    'team.add_btn': 'Add to Team',
    'team.name_placeholder': 'Name (e.g. John Doe)',
    'team.role_placeholder': 'Role (e.g. Developer)',
    'team.total': 'Total Members',
    'team.skills': 'Skills (comma separated)',
    'team.email': 'Email',
    'team.department': 'Department',
    'team.workload': 'Workload',
    'team.active_tasks': 'Active Tasks',
    'team.required_error': 'Name and Role are required',
    'team.added': 'Team member added',
    'team.updated': 'Team member updated',
    'team.removed': 'Member removed',
    'team.remove_title': 'Remove Team Member?',
    'team.remove_warning': 'Warning: This member has active tasks. Removing them will leave these tasks unassigned.',
    'team.remove_confirm': 'Are you sure you want to remove this member?',
    'team.total_suffix': 'Total',
    // AI Assistant
    'audit.btn': 'AI Audit',
    'audit.title': 'Project AI Analyst',
    'audit.intro': 'I can analyze this project for scheduling risks and optimization opportunities.',
    'audit.start': 'Start Analysis',
    'audit.analyzing': 'Analyzing schedule data...',
    'audit.reanalyze': 'Re-analyze',
    // Task Detail
    'task.detail': 'Task Details',
    'task.checklist': 'Checklist',
    'task.comments': 'Comments',
    'task.activity': 'Activity & Comments',
    'task.ai_breakdown': 'AI Breakdown',
    'task.add_item': 'Add Item',
    'task.add_comment': 'Post Comment',
    'task.enter_comment': 'Write a comment...',
    'task.enter_item': 'New checklist item...',
    'task.no_comments': 'No comments yet.',
    'task.no_checklist': 'No checklist items.',
    'task.linked_docs': 'Knowledge Base Links',
    'task.link_doc_placeholder': 'Search docs to link...',
    'task.link_goal': 'Link to Goal',
    'task.select_goal': 'Select a strategic goal...',
    'task.high_priority': 'High Priority',
    'task.add_desc': 'Add a more detailed description...',
    'task.commenting_as': 'Commenting as:',
    'task.select_user': 'Select User',
    'task.phase': 'Phase',
    'task.assignee': 'Assignee',
    'task.assets': 'Assets',
    'task.add_asset': 'Add Link or Doc',
    'task.search_docs': 'Search docs...',
    'task.no_docs': 'No docs found.',
    'task.ai_checklist_success': 'Checklist items generated!',
    'task.ai_checklist_fail': 'AI Breakdown failed',
    'task.comment_deleted': 'Comment deleted',
    'task.save_changes': 'Save Changes',
    // Goals
    'goals.title': 'Goals & OKRs',
    'goals.add': 'New Goal',
    'goals.progress': 'Progress',
    'goals.linked_tasks': 'Linked Tasks',
    'goals.status_ontrack': 'On Track',
    'goals.status_atrisk': 'At Risk',
    'goals.status_offtrack': 'Off Track',
    'goals.status_completed': 'Completed',
    'goals.auto_progress': 'Auto-calculated from linked tasks',
    'goals.subtitle': 'Define strategic objectives and track key results.',
    'goals.title_placeholder': 'Goal Title (e.g., Launch MVP by Q4)',
    'goals.desc_placeholder': 'Description / Key Results...',
    'goals.create': 'Create Goal',
    'goals.no_goals': 'No goals set yet. Start by adding a strategic objective.',
    'goals.created': 'New goal created',
    'goals.owner_placeholder': 'Owner Name',
    'goals.due_prefix': 'Due:',
    // Files
    'files.title': 'Central File Hub',
    'files.upload': 'Upload File',
    'files.filter_all': 'All Files',
    'files.filter_img': 'Images',
    'files.filter_doc': 'Documents',
    'files.source': 'Source',
    'files.subtitle': 'Central repository for all project assets and links.',
    'files.search_placeholder': 'Search files...',
    'files.no_results': 'No files found matching your criteria.',
    'files.unknown_user': 'Unknown',
    // Meeting
    'mtg.title': 'Meetings & Minutes',
    'mtg.add': 'New Meeting',
    'mtg.type': 'Meeting Type',
    'mtg.date': 'Date',
    'mtg.attendees': 'Attendees',
    'mtg.minutes': 'Minutes',
    'mtg.action_items': 'Action Items',
    'mtg.convert_task': 'Convert Selection to Task',
    'mtg.convert_tip': 'Select text in the editor to create a task',
    'mtg.linked_tasks': 'Linked Tasks',
    'mtg.templates': 'Templates',
    'mtg.timer': 'Timer',
    'mtg.status_planned': 'Planned',
    'mtg.status_in_progress': 'In Progress',
    'mtg.status_completed': 'Completed',
    'mtg.tpl_standup': 'Daily Standup',
    'mtg.tpl_review': 'Review',
    'mtg.tpl_retro': 'Retrospective',
    'mtg.ai_summary': 'AI Summary',
    'mtg.generating_summary': 'Generating Summary...',
    'mtg.select_phase_title': 'Add Task to Phase',
    'mtg.select_phase_desc': 'Choose where to add this task:',
    'mtg.new_phase_name': 'New Phase Name',
    'mtg.rec_started': 'Recording started...',
    'mtg.rec_not_supported': 'Audio recording not supported. Please upload a file instead.',
    'mtg.mic_not_found': 'No microphone found. Please use the Upload Audio button.',
    'mtg.mic_denied': 'Microphone permission denied. Check settings or upload a file.',
    'mtg.rec_error': 'Error starting recording',
    'mtg.file_too_large': 'File too large (Max 20MB). Please upload a smaller file.',
    'mtg.transcribe_success': 'Audio file transcribed successfully!',
    'mtg.transcribe_fail': 'Transcription failed',
    'mtg.minutes_success': 'Meeting minutes transcribed successfully!',
    'mtg.summary_success': 'Summary & Action Items Generated',
    'mtg.summary_fail': 'Failed to generate summary',
    'mtg.overwrite_confirm': 'Overwrite current content?',
    'mtg.select_text_warn': 'Please select text first',
    'mtg.task_created': 'Task created from selection',
    'mtg.title_placeholder': 'Meeting Title',
    'mtg.no_phases': 'No existing phases',
    // Wiki
    'wiki.title': 'Knowledge Base',
    'wiki.new_page': 'New Page',
    'wiki.search': 'Search docs...',
    'wiki.untitled': 'Untitled',
    'wiki.external': 'External Link',
    'wiki.type_slash': "Type '/' for commands",
    'wiki.linked_tasks': 'Linked Tasks',
    'wiki.html_block': 'Smart HTML',
    'wiki.html_placeholder': 'Describe the UI you want (e.g. "A pricing table with 3 columns")',
    'wiki.html_generate': 'Generate UI',
    'wiki.basic_blocks': 'Basic Blocks',
    'wiki.turn_into': 'Turn Into',
    'wiki.click_to_add': 'Click to add content',
    'wiki.last_edited': 'Last edited',
    'wiki.outline': 'Outline',
    'wiki.no_headings': 'No headings yet.',
    'wiki.no_linked': 'No tasks linked to this page.',
    'wiki.untitled_page': 'Untitled Page',
    'wiki.change_cover': 'Change Cover',
    'wiki.block_text': 'Text',
    'wiki.block_h1': 'Heading 1',
    'wiki.block_h2': 'Heading 2',
    'wiki.block_h3': 'Heading 3',
    'wiki.block_bullet': 'Bulleted List',
    'wiki.block_todo': 'To-do List',
    'wiki.block_quote': 'Quote',
    'wiki.block_code': 'Code',
    'wiki.block_image': 'Image',
    'wiki.block_html': 'Smart HTML',
    'wiki.block_task': 'Linked Task',
    'wiki.block_doc': 'Link to Page',
    'wiki.delete_doc_title': 'Delete Document?',
    'wiki.delete_doc_msg': 'Are you sure you want to delete this document? This action cannot be undone.',
    'wiki.img_placeholder': 'Paste image URL and press Enter...',
    'wiki.quote_placeholder': 'Empty quote',
    'wiki.code_placeholder': '// Type code here',
    'wiki.list_placeholder': 'List item',
    'wiki.todo_placeholder': 'To-do item',
    'wiki.select_placeholder': 'Select a page to start writing',
    'wiki.task_not_found': 'Task not found or deleted',
    'wiki.doc_deleted': 'Document deleted',
    'wiki.ui_gen_success': 'UI Generated',
    'wiki.ui_gen_fail': 'Generation failed',
    'wiki.ui_preview_placeholder': 'UI Preview will appear here.',
    'wiki.block_text_desc': 'Just start writing with plain text.',
    // Notifications
    'notif.title': 'Notifications',
    'notif.mark_read': 'Mark all read',
    'notif.empty': 'No new notifications',
    // Settings
    'settings.profile': 'User Profile',
    'settings.appearance': 'Appearance & Density',
    'settings.language': 'Interface Language',
    'settings.save': 'Save Preferences',
    'settings.ai_config': 'AI Configuration',
    'settings.ai_desc': 'Configure global AI settings here. These keys will be used for the AI Assistant, Project Generator, and Task Breakdown features.',
    'settings.data': 'Data & Storage',
    'settings.backup': 'Backup & Restore',
    'settings.export': 'Export Data',
    'settings.import': 'Import Data',
    'settings.danger': 'Danger Zone',
    'settings.reset_desc': 'Resetting will wipe all data stored in the database. Make sure you have exported a backup before proceeding.',
    'settings.reset_btn': 'Reset All App Data',
    'settings.shortcuts': 'Keyboard Shortcuts',
    'settings.about': 'About',
    'settings.workspace': 'Workspace Configuration',
    'settings.display_name': 'Display Name',
    'settings.role_title': 'Role / Title',
    'settings.version': 'v1.3.0 with IndexedDB',
    'settings.app_desc': 'A modern, AI-powered project management workspace designed for speed and simplicity.',
    'settings.meta_version': 'Version',
    'settings.meta_license': 'License',
    'settings.meta_stack': 'Stack',
    'settings.meta_ai_model': 'AI Model',
    'settings.reset_title': 'Reset All Data?',
    'settings.reset_confirm': 'Reset Everything',
    'settings.pref_updated': 'Preferences updated',
    'settings.ai_saved': 'AI Configuration saved',
    'settings.export_success': 'Data exported successfully',
    'settings.export_fail': 'Export failed',
    'settings.import_title': 'Import Data?',
    'settings.import_desc': 'This will overwrite your current data with the backup file. Existing projects will be replaced.',
    'settings.import_confirm': 'Overwrite & Import',
    'settings.invalid_backup': 'Invalid backup file',
    // Finance
    'fin.budget': 'Budget & Finance',
    'fin.total_budget': 'Total Budget',
    'fin.total_spent': 'Total Spent',
    'fin.remaining': 'Remaining',
    'fin.burn': 'Budget Burn',
    'fin.used': 'Used',
    'fin.log': 'Expense Log',
    'fin.manage_cats': 'Manage Categories',
    'fin.log_btn': 'Log Expense',
    'fin.desc': 'Description',
    'fin.amount': 'Amount',
    'fin.no_expenses': 'No expenses recorded yet.',
    'fin.cat_exists': 'Category already exists',
    'fin.cat_added': 'Category added',
    'fin.cat_removed': 'Category removed',
    'fin.expense_logged': 'Expense logged',
    'fin.budget_updated': 'Budget updated',
    'fin.new_cat_placeholder': 'New Category...',
    // Risks
    'risk.register': 'Risk Register',
    'risk.subtitle': 'Identify, assess, and mitigate project risks.',
    'risk.add': 'Add Risk',
    'risk.mitigation': 'Mitigation Plan',
    'risk.probability': 'Probability',
    'risk.impact': 'Impact',
    'risk.save': 'Save Risk',
    'risk.issue': 'Risk / Issue',
    'risk.level': 'Level',
    'risk.no_risks': 'No risks recorded. Stay safe!',
    'risk.ai_detect': 'AI Detect',
    'risk.prob_short': 'Prob',
    'risk.impact_short': 'Impact',
    'risk.desc_placeholder': 'e.g., Server downtime',
    'risk.mitigation_placeholder': 'e.g., Setup backup regions',
    'risk.ai_success': 'risks identified by AI',
    'risk.ai_fail': 'Failed to generate risks',
    // Portfolio
    'port.title': 'Global Portfolio',
    'port.subtitle': 'High-level overview across active projects.',
    'port.active': 'Active Projects',
    'port.global_completion': 'Global Completion',
    'port.risk_projects': 'Projects at Risk',
    'port.open_tasks': 'Open Tasks',
    'port.timeline': 'Project Timeline & Health',
    'port.heatmap': 'Resource Heatmap',
    'port.no_assignments': 'No active assignments.',
    'port.optimal': 'Optimal',
    'port.busy': 'Busy',
    'port.overload': 'Overload',
    'port.manager_prefix': 'Manager:',
    'port.risk_badge': 'Risk',
    // Gantt
    'gantt.task_list': 'Task List',
    'gantt.today': 'Today',
    'gantt.delete_dep_msg': 'Delete dependency connection?',
    'gantt.dep_removed': 'Dependency connection removed',
    'gantt.dep_created': 'Dependency created',
    // Calendar
    'cal.today': 'Today',
    // Chat
    'chat.title': 'Project Chat',
    'chat.powered': 'Powered by Gemini',
    'chat.clear': 'Clear History',
    'chat.placeholder': 'Ask about the project...',
    'chat.intro': "Hello! I'm the AI assistant for **{projectName}**. Ask me about task progress, team assignments, or risk analysis.",
    'chat.cleared': 'Context cleared. You can ask new questions.',
    'chat.error': 'Chat Error',
    'chat.error_response': 'Sorry, I encountered an error processing your request.',
  },
  zh: {
    // Common
    'common.search': '搜索任务、负责人...',
    'common.filter': '所有状态',
    'common.add': '添加',
    'common.delete': '删除',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.edit': '编辑',
    'common.done': '完成',
    'common.close': '关闭',
    'common.note': '备注',
    'common.warn': '警告',
    'common.back': '返回',
    'common.select': '选择',
    'common.create': '创建',
    'common.save_changes': '保存更改',
    'common.confirm': '确认',
    // App
    'app.title': 'Gen-项目管理',
    'app.desc': 'AI 驱动的项目管理工具',
    'app.view.dashboard': '项目仪表盘',
    'app.view.projects': '项目',
    'app.view.list': '列表',
    'app.view.board': '看板',
    'app.view.gantt': '甘特图',
    'app.view.calendar': '日历',
    'app.view.meetings': '会议记录',
    'app.view.wiki': '知识库',
    'app.view.goals': '目标 & 战略',
    'app.view.files': '文件中心',
    'app.view.finance': '财务',
    'app.view.issues': '问题跟踪',
    'app.view.risks': '风险',
    'app.export': '导出 CSV',
    'app.team': '团队管理',
    'app.ai_generate': 'AI 生成',
    'app.new_phase': '新阶段',
    'app.no_data': '暂无数据',
    'app.create_phase': '创建阶段',
    'app.gen_ai': '使用 AI 生成',
    'app.switch_lang': 'English',
    // Project Meta
    'project.back': '返回项目库',
    'project.name_label': '项目名称',
    'project.desc_label': '项目描述',
    'project.manager_label': '项目经理',
    'project.created': '创建时间',
    'project.unnamed': '未命名项目',
    'project.no_desc': '暂无描述',
    'project.delete_confirm_title': '删除项目？',
    'project.delete_confirm_msg': '这将永久删除该项目及其所有关联任务、会议和文档。',
    'project.code': '代号',
    'project.budget_total': '总预算',
    'project.settings_title': '项目设置',
    // Dashboard
    'dash.total_tasks': '总任务数',
    'dash.completion_rate': '完成率',
    'dash.pending_items': '待办事项',
    'dash.delayed': '延期/风险',
    'dash.team_workload': '团队工作量',
    'dash.status_dist': '任务状态分布',
    'dash.upcoming': '即将到期',
    'dash.no_upcoming': '近期无截止任务',
    'dash.recent_activity': '最近动态',
    'dash.phase_progress': '阶段进度',
    // ProjectTable
    'table.phase_tasks': '个任务',
    'table.add_task': '添加任务',
    'table.task_name': '任务名称',
    'table.description': '任务描述',
    'table.deliverables': '交付物',
    'table.wait_for': '等待: ',
    'table.status': '状态',
    'table.priority': '优先级',
    'table.schedule': '排期',
    'table.assigned_to': '负责人',
    'table.overdue': '逾期',
    'table.days': '天',
    'table.set_duration': '设置工期',
    'table.start_date': '开始日期',
    'table.end_date': '结束日期',
    'table.link_name': '名称 (如 Figma)',
    'table.link_url': '链接 (https://...)',
    'table.add_link': '添加链接',
    'table.attachments': '附件',
    'table.no_links': '暂无链接',
    'table.wait_tasks': '等待任务:',
    'table.delete_task_confirm': '确定删除此任务吗？',
    'table.serial_number': '序号',
    // Status
    'status.Pending': '待办',
    'status.In Progress': '进行中',
    'status.Completed': '已完成',
    'status.Delayed': '延期',
    'status.All': '所有状态',
    // Priority
    'priority.Low': '低',
    'priority.Med': '中',
    'priority.High': '高',
    // AI Generator
    'ai.title': 'AI 项目架构师',
    'ai.subtitle': "描述您想构建的内容，我将为您创建结构化的计划。",
    'ai.subtitle.settings': '配置您的 AI 提供商',
    'ai.placeholder': '例如：组织一次技术会议...',
    'ai.btn.generate': '生成计划',
    'ai.btn.generating': '生成中...',
    'ai.btn.import': '导入项目',
    'ai.preview': '预览生成计划',
    'ai.start_over': '重新开始',
    'ai.settings': '设置',
    'ai.provider': 'AI 提供商',
    'ai.api_key': 'API 密钥',
    'ai.model': '模型名称',
    'ai.base_url': 'Base URL',
    'ai.cancel': '取消',
    'ai.save_config': '保存配置',
    'ai.thinking': '思考中...',
    'ai.phase': '阶段',
    'ai.target_project': '所属项目',
    'ai.structure_type': '生成结构',
    'ai.structure.full': '完整项目 (多个阶段)',
    'ai.structure.single': '单个阶段 (任务列表)',
    'ai.select_project': '选择一个项目...',
    // Kanban
    'kanban.move_to': '移动到:',
    'kanban.drop': '拖拽任务到此处',
    'kanban.no_phases': '暂无阶段',
    // Team
    'team.title': '团队目录',
    'team.subtitle': '管理团队，查看工作量和任务分配。',
    'team.add_new': '添加成员',
    'team.current': '当前成员',
    'team.add_btn': '添加到团队',
    'team.name_placeholder': '姓名 (如 张三)',
    'team.role_placeholder': '角色 (如 开发人员)',
    'team.total': '成员总数',
    'team.skills': '技能 (逗号分隔)',
    'team.email': '邮箱',
    'team.department': '部门',
    'team.workload': '工作量',
    'team.active_tasks': '活跃任务',
    'team.required_error': '姓名和角色为必填项',
    'team.added': '成员已添加',
    'team.updated': '成员信息已更新',
    'team.removed': '成员已移除',
    'team.remove_title': '移除团队成员？',
    'team.remove_warning': '警告：该成员仍有活跃任务。移除后这些任务将变为未分配状态。',
    'team.remove_confirm': '确定要移除该成员吗？',
    'team.total_suffix': '总数',
    // AI Assistant
    'audit.btn': 'AI 审计',
    'audit.title': '项目 AI 分析师',
    'audit.intro': '我可以分析该项目的进度风险和优化机会。',
    'audit.start': '开始分析',
    'audit.analyzing': '正在分析进度数据...',
    'audit.reanalyze': '重新分析',
    // Task Detail
    'task.detail': '任务详情',
    'task.checklist': '检查清单',
    'task.comments': '评论',
    'task.activity': '动态与评论',
    'task.ai_breakdown': 'AI 拆解',
    'task.add_item': '添加子项',
    'task.add_comment': '发布评论',
    'task.enter_comment': '写下评论...',
    'task.enter_item': '新检查项...',
    'task.no_comments': '暂无评论',
    'task.no_checklist': '暂无检查项',
    'task.linked_docs': '知识库关联',
    'task.link_doc_placeholder': '搜索文档以关联...',
    'task.link_goal': '关联目标',
    'task.select_goal': '选择一个战略目标...',
    'task.high_priority': '高优先级',
    'task.add_desc': '添加更详细的描述...',
    'task.commenting_as': '评论身份:',
    'task.select_user': '选择用户',
    'task.phase': '阶段',
    'task.assignee': '负责人',
    'task.assets': '资产',
    'task.add_asset': '添加链接或文档',
    'task.search_docs': '搜索文档...',
    'task.no_docs': '未找到文档。',
    'task.ai_checklist_success': '检查项已生成！',
    'task.ai_checklist_fail': 'AI 拆解失败',
    'task.comment_deleted': '评论已删除',
    'task.save_changes': '保存更改',
    // Meeting
    'mtg.title': '会议记录',
    'mtg.add': '新建会议',
    'mtg.type': '会议类型',
    'mtg.date': '日期',
    'mtg.attendees': '参会人',
    'mtg.minutes': '会议纪要',
    'mtg.action_items': '行动项 (Action Items)',
    'mtg.convert_task': '选中转任务',
    'mtg.convert_tip': '在编辑器中选中文字以创建任务',
    'mtg.linked_tasks': '关联任务',
    'mtg.templates': '模板',
    'mtg.timer': '计时器',
    'mtg.status_planned': '计划中',
    'mtg.status_in_progress': '进行中',
    'mtg.status_completed': '已结束',
    'mtg.tpl_standup': '每日站会',
    'mtg.tpl_review': '需求评审',
    'mtg.tpl_retro': '复盘回顾',
    'mtg.ai_summary': 'AI 总结',
    'mtg.generating_summary': '正在生成总结...',
    'mtg.select_phase_title': '添加任务到阶段',
    'mtg.select_phase_desc': '选择要将任务添加到哪个阶段：',
    'mtg.new_phase_name': '新阶段名称',
    'mtg.rec_started': '录音已开始...',
    'mtg.rec_not_supported': '不支持音频录制，请上传文件。',
    'mtg.mic_not_found': '未找到麦克风，请使用上传功能。',
    'mtg.mic_denied': '麦克风权限被拒绝，请检查设置。',
    'mtg.rec_error': '录音启动失败',
    'mtg.file_too_large': '文件过大 (最大 20MB)，请上传较小的文件。',
    'mtg.transcribe_success': '音频转录成功！',
    'mtg.transcribe_fail': '转录失败',
    'mtg.minutes_success': '会议纪要转录成功！',
    'mtg.summary_success': '总结和行动项已生成',
    'mtg.summary_fail': '生成总结失败',
    'mtg.overwrite_confirm': '覆盖当前内容？',
    'mtg.select_text_warn': '请先选择文本',
    'mtg.task_created': '已从选中内容创建任务',
    'mtg.title_placeholder': '会议标题',
    'mtg.no_phases': '无现有阶段',
    // Wiki
    'wiki.title': '知识库',
    'wiki.new_page': '新建页面',
    'wiki.search': '搜索文档...',
    'wiki.untitled': '无标题页面',
    'wiki.external': '外部链接',
    'wiki.type_slash': "输入 '/' 唤起命令",
    'wiki.linked_tasks': '反向关联任务',
    'wiki.html_block': '智能 HTML',
    'wiki.html_placeholder': '描述你想要的 UI (例如：三栏定价表，包含价格和按钮)',
    'wiki.html_generate': '生成 UI',
    'wiki.basic_blocks': '基础块',
    'wiki.turn_into': '转换为',
    'wiki.click_to_add': '点击添加内容',
    'wiki.last_edited': '最后编辑',
    'wiki.outline': '大纲',
    'wiki.no_headings': '暂无标题。',
    'wiki.no_linked': '此页面未关联任务。',
    'wiki.untitled_page': '无标题页面',
    'wiki.change_cover': '更换封面',
    'wiki.block_text': '文本',
    'wiki.block_h1': '标题 1',
    'wiki.block_h2': '标题 2',
    'wiki.block_h3': '标题 3',
    'wiki.block_bullet': '无序列表',
    'wiki.block_todo': '待办列表',
    'wiki.block_quote': '引用',
    'wiki.block_code': '代码',
    'wiki.block_image': '图片',
    'wiki.block_html': '智能 HTML',
    'wiki.block_task': '关联任务',
    'wiki.block_doc': '页面链接',
    'wiki.delete_doc_title': '删除文档？',
    'wiki.delete_doc_msg': '确定要删除此文档吗？此操作无法撤销。',
    'wiki.img_placeholder': '粘贴图片 URL 并回车...',
    'wiki.quote_placeholder': '空引用',
    'wiki.code_placeholder': '// 在此输入代码',
    'wiki.list_placeholder': '列表项',
    'wiki.todo_placeholder': '待办项',
    'wiki.select_placeholder': '选择一个页面开始写作',
    'wiki.task_not_found': '任务未找到或已删除',
    'wiki.doc_deleted': '文档已删除',
    'wiki.ui_gen_success': 'UI 已生成',
    'wiki.ui_gen_fail': '生成失败',
    'wiki.ui_preview_placeholder': 'UI 预览将在此显示。',
    'wiki.block_text_desc': '开始输入纯文本。',
    // Goals
    'goals.title': '目标与 OKR',
    'goals.add': '新目标',
    'goals.progress': '进度',
    'goals.linked_tasks': '关联任务数',
    'goals.status_ontrack': '正常',
    'goals.status_atrisk': '有风险',
    'goals.status_offtrack': '偏离',
    'goals.status_completed': '已完成',
    'goals.auto_progress': '基于关联任务自动计算',
    'goals.subtitle': '定义战略目标并跟踪关键结果。',
    'goals.title_placeholder': '目标标题 (例如：Q4 发布 MVP)',
    'goals.desc_placeholder': '描述 / 关键结果...',
    'goals.create': '创建目标',
    'goals.no_goals': '暂无目标。请先添加战略目标。',
    'goals.created': '新目标已创建',
    'goals.owner_placeholder': '负责人姓名',
    'goals.due_prefix': '截止:',
    // Files
    'files.title': '文件资源中心',
    'files.upload': '上传文件',
    'files.filter_all': '全部文件',
    'files.filter_img': '图片',
    'files.filter_doc': '文档',
    'files.source': '来源',
    'files.subtitle': '所有项目资产和链接的中央存储库。',
    'files.search_placeholder': '搜索文件...',
    'files.no_results': '未找到匹配的文件。',
    'files.unknown_user': '未知用户',
    // Notifications
    'notif.title': '通知',
    'notif.mark_read': '全部已读',
    'notif.empty': '暂无新通知',
    // Settings
    'settings.profile': '个人资料',
    'settings.appearance': '外观与密度',
    'settings.language': '界面语言',
    'settings.save': '保存偏好设置',
    'settings.ai_config': 'AI 配置',
    'settings.ai_desc': '在此配置全局 AI 设置。这些密钥将用于 AI 助手、项目生成器和任务拆解功能。',
    'settings.data': '数据管理',
    'settings.backup': '备份与恢复',
    'settings.export': '导出数据',
    'settings.import': '导入数据',
    'settings.danger': '危险区域',
    'settings.reset_desc': '重置将清除数据库中的所有数据。请确保在继续之前已导出备份。',
    'settings.reset_btn': '重置所有应用数据',
    'settings.shortcuts': '键盘快捷键',
    'settings.about': '关于软件',
    'settings.workspace': '工作区配置',
    'settings.display_name': '显示名称',
    'settings.role_title': '角色 / 职位',
    'settings.version': 'v1.3.0 (IndexedDB)',
    'settings.app_desc': '专为速度和简洁而设计的现代化 AI 项目管理工作区。',
    'settings.meta_version': '版本',
    'settings.meta_license': '许可',
    'settings.meta_stack': '技术栈',
    'settings.meta_ai_model': 'AI 模型',
    'settings.reset_title': '重置所有数据？',
    'settings.reset_confirm': '全部重置',
    'settings.pref_updated': '偏好设置已更新',
    'settings.ai_saved': 'AI 配置已保存',
    'settings.export_success': '数据导出成功',
    'settings.export_fail': '导出失败',
    'settings.import_title': '导入数据？',
    'settings.import_desc': '这将使用备份文件覆盖当前数据。现有项目将被替换。',
    'settings.import_confirm': '覆盖并导入',
    'settings.invalid_backup': '无效的备份文件',
    // Finance
    'fin.budget': '预算与财务',
    'fin.total_budget': '总预算',
    'fin.total_spent': '总支出',
    'fin.remaining': '剩余预算',
    'fin.burn': '预算消耗',
    'fin.used': '已用',
    'fin.log': '支出记录',
    'fin.manage_cats': '管理分类',
    'fin.log_btn': '记录支出',
    'fin.desc': '描述',
    'fin.amount': '金额',
    'fin.no_expenses': '暂无支出记录。',
    'fin.cat_exists': '分类已存在',
    'fin.cat_added': '分类已添加',
    'fin.cat_removed': '分类已移除',
    'fin.expense_logged': '支出已记录',
    'fin.budget_updated': '预算已更新',
    'fin.new_cat_placeholder': '新分类...',
    // Risks
    'risk.register': '风险登记册',
    'risk.subtitle': '识别、评估和减轻项目风险。',
    'risk.add': '添加风险',
    'risk.mitigation': '缓解计划',
    'risk.probability': '可能性',
    'risk.impact': '影响',
    'risk.save': '保存风险',
    'risk.issue': '风险/问题',
    'risk.level': '等级',
    'risk.no_risks': '暂无风险记录。保持安全！',
    'risk.ai_detect': 'AI 检测',
    'risk.prob_short': '概率',
    'risk.impact_short': '影响',
    'risk.desc_placeholder': '例如：服务器宕机',
    'risk.mitigation_placeholder': '例如：建立备份区域',
    'risk.ai_success': 'AI 识别到的风险',
    'risk.ai_fail': '生成风险失败',
    // Portfolio
    'port.title': '全局概览',
    'port.subtitle': '活跃项目的高级概览。',
    'port.active': '活跃项目',
    'port.global_completion': '全局完成率',
    'port.risk_projects': '风险项目',
    'port.open_tasks': '待办任务',
    'port.timeline': '项目时间轴与健康度',
    'port.heatmap': '资源热力图',
    'port.no_assignments': '无活跃分配。',
    'port.optimal': '最佳',
    'port.busy': '繁忙',
    'port.overload': '过载',
    'port.manager_prefix': '经理:',
    'port.risk_badge': '风险',
    // Gantt
    'gantt.task_list': '任务列表',
    'gantt.today': '今天',
    'gantt.delete_dep_msg': '删除依赖关系？',
    'gantt.dep_removed': '依赖关系已移除',
    'gantt.dep_created': '依赖关系已创建',
    // Calendar
    'cal.today': '今天',
    // Chat
    'chat.title': '项目助手',
    'chat.powered': '由 Gemini 驱动',
    'chat.clear': '清除历史',
    'chat.placeholder': '询问关于项目的问题...',
    'chat.intro': '你好！我是 **{projectName}** 的 AI 助手。你可以问我关于任务进度、团队分工或风险分析的问题。',
    'chat.cleared': '已清空上下文。你可以重新开始提问。',
    'chat.error': '聊天错误',
    'chat.error_response': '抱歉，处理您的请求时遇到错误。',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
