
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'common.search': 'Search tasks, owners...',
    'common.filter': 'All Statuses',
    'common.add': 'Add',
    'common.delete': 'Delete',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.done': 'Done',
    'common.close': 'Close',
    'common.note': 'Note',
    'common.warn': 'Warn',
    'common.back': 'Back',
    'common.select': 'Select',
    'common.create': 'Create',
    'common.save_changes': 'Save Changes',
    'common.confirm': 'Confirm',
    'common.attention': 'Attention',
    'common.error': 'Error',
    // App
    'app.title': 'Gen-Project Manager',
    'app.desc': 'AI-Powered Project Management',
    'app.view.dashboard': 'Dashboard',
    'app.view.projects': 'Projects',
    'app.view.list': 'List',
    'app.view.board': 'Board',
    'app.view.gantt': 'Gantt',
    'app.view.calendar': 'Calendar',
    'app.view.meetings': 'Meetings',
    'app.view.wiki': 'Knowledge Base',
    'app.view.goals': 'Goals & Strategy',
    'app.view.files': 'File Hub',
    'app.view.finance': 'Finance',
    'app.view.issues': 'Issue Tracker',
    'app.view.risks': 'Risks',
    'app.view.super_table': 'Super Table',
    'app.export': 'Export CSV',
    'app.team': 'Team',
    'app.ai_generate': 'AI Generate',
    'app.new_phase': 'New Phase',
    'app.no_data': 'No data available.',
    'app.create_phase': 'Create Phase',
    'app.gen_ai': 'Generate with AI',
    'app.switch_lang': '中文',
    'app.project_name_exists': 'Project name already exists. Please use a different name.',
    // Project Meta
    'project.back': 'Back to Projects',
    'project.name_label': 'Project Name',
    'project.desc_label': 'Description',
    'project.manager_label': 'Project Manager',
    'project.created': 'Created',
    'project.unnamed': 'Unnamed Project',
    'project.no_desc': 'No description provided.',
    'project.delete_confirm_title': 'Delete Project?',
    'project.delete_confirm_msg': 'This will permanently delete the project and all associated tasks, meetings, and documents.',
    'project.code': 'Code',
    'project.budget_total': 'Total Budget',
    'project.settings_title': 'Project Settings',
    // Dashboard
    'dash.total_tasks': 'Total Tasks',
    'dash.completion_rate': 'Completion Rate',
    'dash.pending_items': 'Pending Items',
    'dash.delayed': 'Delayed / Risk',
    'dash.team_workload': 'Team Workload',
    'dash.status_dist': 'Task Status Distribution',
    'dash.upcoming': 'Upcoming Deadlines',
    'dash.no_upcoming': 'No immediate deadlines.',
    'dash.recent_activity': 'Recent Activity',
    'dash.phase_progress': 'Phase Progress',
    // ProjectTable
    'table.phase_tasks': 'tasks',
    'table.add_task': 'Add Task',
    'table.task_name': 'Task Name',
    'table.description': 'Task Description',
    'table.deliverables': 'Deliverables',
    'table.wait_for': 'Wait: ',
    'table.status': 'Status',
    'table.priority': 'Priority',
    'table.schedule': 'Schedule',
    'table.assigned_to': 'Assigned To',
    'table.overdue': 'Overdue',
    'table.days': 'days',
    'table.set_duration': 'Set Duration',
    'table.start_date': 'Start Date',
    'table.end_date': 'End Date',
    'table.link_name': 'Name (e.g. Figma)',
    'table.link_url': 'URL (https://...)',
    'table.add_link': 'Add Link',
    'table.attachments': 'Attachments',
    'table.no_links': 'No links yet.',
    'table.wait_tasks': 'Wait for tasks:',
    'table.delete_task_confirm': 'Delete this task?',
    'table.serial_number': 'No.',
    // Status
    'status.Pending': 'Pending',
    'status.In Progress': 'In Progress',
    'status.Completed': 'Completed',
    'status.Delayed': 'Delayed',
    'status.Open': 'Open',
    'status.Planning': 'Planning',
    'status.Closed': 'Closed',
    'status.All': 'All Statuses',
    // Priority
    'priority.Low': 'Low',
    'priority.Med': 'Med',
    'priority.High': 'High',
    // AI Generator
    'ai.title': 'AI Project Architect',
    'ai.subtitle': "Describe what you want to build, and I'll create a structured plan.",
    'ai.subtitle.settings': 'Configure your AI Provider',
    'ai.placeholder': 'e.g., Organize a Tech Conference ...',
    'ai.btn.generate': 'Generate Plan',
    'ai.btn.generating': 'Generating...',
    'ai.btn.import': 'Import to Project',
    'ai.preview': 'Preview Generated Plan',
    'ai.start_over': 'Start Over',
    'ai.settings': 'Settings',
    'ai.provider': 'AI Provider',
    'ai.api_key': 'API Key',
    'ai.model': 'Model Name',
    'ai.base_url': 'Base URL',
    'ai.cancel': 'Cancel',
    'ai.save_config': 'Save Configuration',
    'ai.thinking': 'Thinking...',
    'ai.phase': 'PHASE',
    'ai.target_project': 'Target Project',
    'ai.structure_type': 'Structure Type',
    'ai.structure.full': 'Full Project (Multiple Phases)',
    'ai.structure.single': 'Single Phase (Task List)',
    'ai.select_project': 'Select a Project...',
    // Kanban
    'kanban.move_to': 'Move to:',
    'kanban.drop': 'Drop items here',
    'kanban.no_phases': 'No existing phases',
    // Team
    'team.title': 'Team Directory',
    'team.subtitle': 'Manage your team, view workloads, and track assignments.',
    'team.add_new': 'Add Member',
    'team.current': 'Current Members',
    'team.add_btn': 'Add to Team',
    'team.name_placeholder': 'Name (e.g. John Doe)',
    'team.role_placeholder': 'Role (e.g. Developer)',
    'team.total': 'Total Members',
    'team.skills': 'Skills (comma separated)',
    'team.email': 'Email',
    'team.department': 'Department',
    'team.workload': 'Workload',
    'team.active_tasks': 'Active Tasks',
    'team.required_error': 'Name and Role are required',
    'team.added': 'Team member added',
    'team.updated': 'Team member updated',
    'team.removed': 'Member removed',
    'team.remove_title': 'Remove Team Member?',
    'team.remove_warning': 'Warning: This member has active tasks. Removing them will leave these tasks unassigned.',
    'team.remove_confirm': 'Are you sure you want to remove this member?',
    'team.total_suffix': 'Total',
    // AI Assistant
    'audit.btn': 'AI Audit',
    'audit.title': 'Project AI Analyst',
    'audit.intro': 'I can analyze this project for scheduling risks and optimization opportunities.',
    'audit.start': 'Start Analysis',
    'audit.analyzing': 'Analyzing schedule data...',
    'audit.reanalyze': 'Re-analyze',
    // Task Detail
    'task.detail': 'Task Details',
    'task.checklist': 'Checklist',
    'task.comments': 'Comments',
    'task.activity': 'Activity & Comments',
    'task.ai_breakdown': 'AI Breakdown',
    'task.add_item': 'Add Item',
    'task.add_comment': 'Post Comment',
    'task.enter_comment': 'Write a comment...',
    'task.enter_item': 'New checklist item...',
    'task.no_comments': 'No comments yet.',
    'task.no_checklist': 'No checklist items.',
    'task.linked_docs': 'Knowledge Base Links',
    'task.link_doc_placeholder': 'Search docs to link...',
    'task.link_goal': 'Link to Goal',
    'task.select_goal': 'Select a strategic goal...',
    'task.high_priority': 'High Priority',
    'task.add_desc': 'Add a more detailed description...',
    'task.commenting_as': 'Commenting as:',
    'task.select_user': 'Select User',
    'task.phase': 'Phase',
    'task.assignee': 'Assignee',
    'task.assets': 'Assets',
    'task.add_asset': 'Add Link or Doc',
    'task.search_docs': 'Search docs...',
    'task.no_docs': 'No docs found.',
    'task.ai_checklist_success': 'Checklist items generated!',
    'task.ai_checklist_fail': 'AI Breakdown failed',
    'task.comment_deleted': 'Comment deleted',
    'task.save_changes': 'Save Changes',
    // Goals
    'goals.title': 'Goals & OKRs',
    'goals.add': 'New Goal',
    'goals.progress': 'Progress',
    'goals.linked_tasks': 'Linked Tasks',
    'goals.status_ontrack': 'On Track',
    'goals.status_atrisk': 'At Risk',
    'goals.status_offtrack': 'Off Track',
    'goals.status_completed': 'Completed',
    'goals.auto_progress': 'Auto-calculated from linked tasks',
    'goals.subtitle': 'Define strategic objectives and track key results.',
    'goals.title_placeholder': 'Goal Title (e.g., Launch MVP by Q4)',
    'goals.desc_placeholder': 'Description / Key Results...',
    'goals.create': 'Create Goal',
    'goals.no_goals': 'No goals set yet. Start by adding a strategic objective.',
    'goals.created': 'New goal created',
    'goals.owner_placeholder': 'Owner Name',
    'goals.due_prefix': 'Due:',
    // Files
    'files.title': 'Central File Hub',
    'files.upload': 'Upload File',
    'files.filter_all': 'All Files',
    'files.filter_img': 'Images',
    'files.filter_doc': 'Documents',
    'files.source': 'Source',
    'files.subtitle': 'Central repository for all project assets and links.',
    'files.search_placeholder': 'Search files...',
    'files.no_results': 'No files found matching your criteria.',
    'files.unknown_user': 'Unknown',
    // Meeting
    'mtg.title': 'Meetings & Minutes',
    'mtg.add': 'New Meeting',
    'mtg.type': 'Meeting Type',
    'mtg.date': 'Date',
    'mtg.attendees': 'Attendees',
    'mtg.minutes': 'Minutes',
    'mtg.action_items': 'Action Items',
    'mtg.convert_task': 'Convert Selection to Task',
    'mtg.convert_tip': 'Select text in the editor to create a task',
    'mtg.linked_tasks': 'Linked Tasks',
    'mtg.templates': 'Templates',
    'mtg.timer': 'Timer',
    'mtg.status_planned': 'Planned',
    'mtg.status_in_progress': 'In Progress',
    'mtg.status_completed': 'Completed',
    'mtg.tpl_standup': 'Daily Standup',
    'mtg.tpl_review': 'Review',
    'mtg.tpl_retro': 'Retrospective',
    'mtg.ai_summary': 'AI Summary',
    'mtg.generating_summary': 'Generating Summary...',
    'mtg.select_phase_title': 'Add Task to Phase',
    'mtg.select_phase_desc': 'Choose where to add this task:',
    'mtg.new_phase_name': 'New Phase Name',
    'mtg.rec_started': 'Recording started...',
    'mtg.rec_not_supported': 'Audio recording not supported. Please upload a file instead.',
    'mtg.mic_not_found': 'No microphone found. Please use the Upload Audio button.',
    'mtg.mic_denied': 'Microphone permission denied. Check settings or upload a file.',
    'mtg.rec_error': 'Error starting recording',
    'mtg.file_too_large': 'File too large (Max 20MB). Please upload a smaller file.',
    'mtg.transcribe_success': 'Audio file transcribed successfully!',
    'mtg.transcribe_fail': 'Transcription failed',
    'mtg.minutes_success': 'Meeting minutes transcribed successfully!',
    'mtg.summary_success': 'Summary & Action Items Generated',
    'mtg.summary_fail': 'Failed to generate summary',
    'mtg.overwrite_confirm': 'Overwrite current content?',
    'mtg.select_text_warn': 'Please select text first',
    'mtg.task_created': 'Task created from selection',
    'mtg.title_placeholder': 'Meeting Title',
    'mtg.no_phases': 'No existing phases',
    // Wiki
    'wiki.title': 'Knowledge Base',
    'wiki.new_page': 'New Page',
    'wiki.search': 'Search docs...',
    'wiki.untitled': 'Untitled',
    'wiki.external': 'External Link',
    'wiki.type_slash': "Type '/' for commands",
    'wiki.linked_tasks': 'Linked Tasks',
    'wiki.html_block': 'Smart HTML',
    'wiki.html_placeholder': 'Describe the UI you want (e.g. "A pricing table with 3 columns")',
    'wiki.html_generate': 'Generate UI',
    'wiki.basic_blocks': 'Basic Blocks',
    'wiki.turn_into': 'Turn Into',
    'wiki.click_to_add': 'Click to add content',
    'wiki.last_edited': 'Last edited',
    'wiki.outline': 'Outline',
    'wiki.no_headings': 'No headings yet.',
    'wiki.no_linked': 'No tasks linked to this page.',
    'wiki.untitled_page': 'Untitled Page',
    'wiki.change_cover': 'Change Cover',
    'wiki.block_text': 'Text',
    'wiki.block_h1': 'Heading 1',
    'wiki.block_h2': 'Heading 2',
    'wiki.block_h3': 'Heading 3',
    'wiki.block_bullet': 'Bulleted List',
    'wiki.block_todo': 'To-do List',
    'wiki.block_quote': 'Quote',
    'wiki.block_code': 'Code',
    'wiki.block_image': 'Image',
    'wiki.block_html': 'Smart HTML',
    'wiki.block_task': 'Linked Task',
    'wiki.block_doc': 'Link to Page',
    'wiki.delete_doc_title': 'Delete Document?',
    'wiki.delete_doc_msg': 'Are you sure you want to delete this document? This action cannot be undone.',
    'wiki.img_placeholder': 'Paste image URL and press Enter...',
    'wiki.quote_placeholder': 'Empty quote',
    'wiki.code_placeholder': '// Type code here',
    'wiki.list_placeholder': 'List item',
    'wiki.todo_placeholder': 'To-do item',
    'wiki.select_placeholder': 'Select a page to start writing',
    'wiki.task_not_found': 'Task not found or deleted',
    'wiki.doc_deleted': 'Document deleted',
    'wiki.ui_gen_success': 'UI Generated',
    'wiki.ui_gen_fail': 'Generation failed',
    'wiki.ui_preview_placeholder': 'UI Preview will appear here.',
    'wiki.block_text_desc': 'Just start writing with plain text.',
    // Notifications
    'notif.title': 'Notifications',
    'notif.mark_read': 'Mark all read',
    'notif.empty': 'No new notifications',
    // Settings
    'settings.profile': 'User Profile',
    'settings.appearance': 'Appearance & Density',
    'settings.language': 'Interface Language',
    'settings.save': 'Save Preferences',
    'settings.ai_config': 'AI Configuration',
    'settings.ai_desc': 'Configure global AI settings here. These keys will be used for the AI Assistant, Project Generator, and Task Breakdown features.',
    'settings.data': 'Data & Storage',
    'settings.backup': 'Backup & Restore',
    'settings.export': 'Export Data',
    'settings.import': 'Import Data',
    'settings.danger': 'Danger Zone',
    'settings.reset_desc': 'Resetting will wipe all data stored in the database. Make sure you have exported a backup before proceeding.',
    'settings.reset_btn': 'Reset All App Data',
    'settings.shortcuts': 'Keyboard Shortcuts',
    'settings.about': 'About',
    'settings.workspace': 'Workspace Configuration',
    'settings.display_name': 'Display Name',
    'settings.role_title': 'Role / Title',
    'settings.version': 'v1.3.0 with IndexedDB',
    'settings.app_desc': 'A modern, AI-powered project management workspace designed for speed and simplicity.',
    'settings.meta_version': 'Version',
    'settings.meta_license': 'License',
    'settings.meta_stack': 'Stack',
    'settings.meta_ai_model': 'AI Model',
    'settings.reset_title': 'Reset All Data?',
    'settings.reset_confirm': 'Reset Everything',
    'settings.pref_updated': 'Preferences updated',
    'settings.ai_saved': 'AI Configuration saved',
    'settings.export_success': 'Data exported successfully',
    'settings.export_fail': 'Export failed',
    'settings.import_title': 'Import Data?',
    'settings.import_desc': 'This will overwrite your current data with the backup file. Existing projects will be replaced.',
    'settings.import_confirm': 'Overwrite & Import',
    'settings.invalid_backup': 'Invalid backup file',
    // Finance
    'fin.budget': 'Budget & Finance',
    'fin.total_budget': 'Total Budget',
    'fin.total_spent': 'Total Spent',
    'fin.remaining': 'Remaining',
    'fin.burn': 'Budget Burn',
    'fin.used': 'Used',
    'fin.log': 'Expense Log',
    'fin.manage_cats': 'Manage Categories',
    'fin.log_btn': 'Log Expense',
    'fin.desc': 'Description',
    'fin.amount': 'Amount',
    'fin.no_expenses': 'No expenses recorded yet.',
    'fin.cat_exists': 'Category already exists',
    'fin.cat_added': 'Category added',
    'fin.cat_removed': 'Category removed',
    'fin.expense_logged': 'Expense logged',
    'fin.budget_updated': 'Budget updated',
    'fin.new_cat_placeholder': 'New Category...',
    // Risks
    'risk.register': 'Risk Register',
    'risk.subtitle': 'Identify, assess, and mitigate project risks.',
    'risk.add': 'Add Risk',
    'risk.mitigation': 'Mitigation Plan',
    'risk.probability': 'Probability',
    'risk.impact': 'Impact',
    'risk.save': 'Save Risk',
    'risk.issue': 'Risk / Issue',
    'risk.level': 'Level',
    'risk.no_risks': 'No risks recorded. Stay safe!',
    'risk.ai_detect': 'AI Detect',
    'risk.prob_short': 'Prob',
    'risk.impact_short': 'Impact',
    'risk.desc_placeholder': 'e.g., Server downtime',
    'risk.mitigation_placeholder': 'e.g., Setup backup regions',
    'risk.ai_success': 'risks identified by AI',
    'risk.ai_fail': 'Failed to generate risks',
    // Portfolio
    'port.title': 'Global Portfolio',
    'port.subtitle': 'High-level overview across active projects.',
    'port.active': 'Active Projects',
    'port.global_completion': 'Global Completion',
    'port.risk_projects': 'Projects at Risk',
    'port.open_tasks': 'Open Tasks',
    'port.timeline': 'Project Timeline & Health',
    'port.heatmap': 'Resource Heatmap',
    'port.no_assignments': 'No active assignments.',
    'port.optimal': 'Optimal',
    'port.busy': 'Busy',
    'port.overload': 'Overload',
    'port.manager_prefix': 'Manager:',
    'port.risk_badge': 'Risk',
    // Gantt
    'gantt.task_list': 'Task List',
    'gantt.today': 'Today',
    'gantt.delete_dep_msg': 'Delete dependency connection?',
    'gantt.dep_removed': 'Dependency connection removed',
    'gantt.dep_created': 'Dependency created',
    // Calendar
    'cal.today': 'Today',
    // Chat
    'chat.title': 'Project Chat',
    'chat.powered': 'Powered by Gemini',
    'chat.clear': 'Clear History',
    'chat.placeholder': 'Ask about the project...',
    'chat.intro': "Hello! I'm the AI assistant for **{projectName}**. Ask me about task progress, team assignments, or risk analysis.",
    'chat.cleared': 'Context cleared. You can ask new questions.',
    'chat.error': 'Chat Error',
    'chat.error_response': 'Sorry, I encountered an error processing your request.',
    // Issue Tracker
    'issue.title': 'Issue Tracker',
    'issue.subtitle': 'Track and manage project issues and anomalies',
    'issue.import_data': 'Import Data',
    'issue.report': 'Report Issue',
    'issue.search_placeholder': 'Search issues...',
    'issue.filter.all_status': 'All Status',
    'issue.filter.all_projects': 'All Projects',
    'issue.table.id': 'ID',
    'issue.table.date': 'Date',
    'issue.table.project': 'Project',
    'issue.table.description': 'Description',
    'issue.table.assets': 'Assets',
    'issue.table.status': 'Status',
    'issue.table.responsible': 'Responsible',
    'issue.table.discovery': 'Discovery',
    'issue.table.resolution': 'Resolution',
    'issue.table.actions': 'Actions',
    'issue.no_issues': 'No issues found matching your filters.',
    'issue.import.title': 'Import Issues',
    'issue.import.desc': 'Paste your Excel/CSV data here. Ensure columns match: ID, Date, Project, System, Main Class, Phase, Sub Class, Reporter, Tracker, Description, Attachments, Root Cause, Responsible, Solution, Status.',
    'issue.import.placeholder': 'Paste tab-separated data here...',
    'issue.import.btn': 'Import Issues',
    'issue.import.error': 'No valid issues found to import. Please ensure data is tab-separated.',
    'issue.import.success': 'Issues imported successfully',
    'issue.delete_title': 'Delete Issue',
    'issue.delete_confirm': 'Are you sure you want to delete this issue?',
    'issue.delete_success': 'Issue deleted successfully',
    'issue.linked_docs': 'Linked Documents',
    'issue.view_images': 'View Images',
    'issue.view_linked_docs': 'View Linked Docs',
    // Issue Modal
    'issue.modal.edit_title': 'Edit Issue',
    'issue.modal.new_title': 'Report New Issue',
    'issue.modal.id_prefix': 'ID: ',
    'issue.modal.new_desc': 'Log a new anomaly or defect',
    'issue.modal.project': 'Project',
    'issue.modal.select_project': 'Select Project',
    'issue.modal.category': 'Issue Stage',
    'issue.modal.category_placeholder': 'e.g. Development, Testing',
    'issue.modal.description': 'Description',
    'issue.modal.description_placeholder': 'Describe the issue in detail...',
    'issue.modal.ai_analyze': 'AI Analyze',
    'issue.modal.ai_analyzing': 'Analyzing...',
    'issue.modal.ai_config_missing': 'AI configuration missing. Please check settings.',
    'issue.modal.ai_error': 'AI Analysis failed. Please check your API key.',
    'issue.modal.attachments': 'Attachments',
    'issue.modal.add_image': 'Add Image',
    'issue.modal.upload_placeholder': 'Click to upload images',
    'issue.modal.root_cause': 'Root Cause Analysis',
    'issue.modal.root_cause_placeholder': 'Why did this happen?',
    'issue.modal.temp_solution': 'Temporary Solution',
    'issue.modal.temp_solution_placeholder': 'Immediate mitigation steps...',
    'issue.modal.root_solution': 'Root Solution',
    'issue.modal.root_solution_placeholder': 'Long term fix to prevent recurrence...',
    'issue.modal.status': 'Status',
    'issue.modal.date_reported': 'Date Reported',
    'issue.modal.discovery_date': 'Discovery Date',
    'issue.modal.resolution_date': 'Resolution Date',
    'issue.modal.people': 'People',
    'issue.modal.reporter': 'Reporter',
    'issue.modal.reporter_placeholder': 'Reporter Name',
    'issue.modal.responsible': 'Responsible',
    'issue.modal.responsible_placeholder': 'Responsible Person',
    'issue.modal.tracker': 'Tracker',
    'issue.modal.tracker_placeholder': 'Tracker Name',
    'issue.modal.device_info': 'Device Info',
    'issue.modal.device_category': 'System',
    'issue.modal.device_category_placeholder': 'e.g. Control System',
    'issue.modal.device_type': 'Major Class',
    'issue.modal.device_type_placeholder': 'e.g. Hardware',
    'issue.modal.source': 'Sub Class',
    'issue.modal.source_placeholder': 'e.g. Sensor',
    'issue.modal.linked_docs': 'Linked Docs',
    'issue.modal.no_docs': 'No docs in this project.',
    'issue.modal.save': 'Save Issue',
    'issue.modal.file_too_large': 'File is too large (max 5MB)',
    'issue.modal.desc_required': 'Description is required',
    'issue.modal.tag_manager_title': 'Tag Library Manager',
    'issue.modal.tag_manager_desc': 'Manage your custom tags for issues',
    'issue.modal.add_tag_placeholder': 'Add new tag...',
    'issue.modal.no_tags_in_cat': 'No tags in this category yet.',
    'issue.modal.tags_found': 'Found {n} unsaved tags',
    'issue.modal.tags_found_desc': 'Tags used in issues but not in library.',
    'issue.modal.import_tags': 'Import All',
    'issue.modal.group_basic': 'Basic Info',
    'issue.modal.group_device': 'Device Info',
    // App Messages
    'app.loading_title': 'Loading Gen-PM',
    'app.loading_desc': 'Initializing Database...',
    'app.refreshed': 'Interface Refreshed',
    'app.load_error': 'Error loading data',
    'app.issue_reported': 'Issue reported successfully',
    'app.issue_updated': 'Issue updated',
    'app.issue_deleted': 'Issue deleted',
    'app.issues_imported': 'Imported issues',
    'app.project_created': 'New project created',
    'app.project_deleted': 'Project deleted',
    'app.meeting_deleted': 'Meeting deleted',
    'app.event_updated': 'Event updated successfully',
    'app.event_created': 'Event created successfully',
    'app.event_deleted': 'Event deleted',
    'app.sync_success': 'Sync completed successfully',
    'app.sync_fail': 'Sync failed. Check connection.',
    'app.workspace': 'Workspace',
    'app.quick_sync': 'Quick Sync to Cloud',
    'app.search_placeholder': 'Search...',
    'app.delete_meeting_confirm': 'Are you sure you want to delete this meeting? This action cannot be undone.',
    // Kanban
    'kanban.unassigned': 'Unassigned',
    // SuperTable / ERP
    'erp.title': 'Super Table',
    'erp.subtitle': 'Data Management Hub',
    'erp.tab.data': 'Data',
    'erp.tab.builder': 'Builder',
    'erp.tab.library': 'Library',
    'erp.tab.product_center': 'Product Center',
    'erp.tab.guide': 'Guide',
    'erp.sub.config': 'Define Product',
    'erp.sub.library': 'Product Library',
    'erp.sub.settings': 'Settings',
    'erp.view.table': 'Table View',
    'erp.view.preview': 'Preview',
    'erp.view.batch': 'Batch Entry',
    'erp.my_data': 'My Data',
    'erp.add_dataset': 'Add Dataset',
    'erp.add_folder': 'Add Folder',
    'erp.save_dataset': 'Save Dataset',
    'erp.new_dataset': 'New Dataset',
    'erp.form_templates': 'Form Templates',
    'erp.quick_start': 'Quick Start',
    'erp.new_template': 'New Template',
    'erp.save_template': 'Save as Template',
    'erp.load_template': 'Load Template',
    'erp.untitled': 'Untitled',
    'erp.field_name': 'Field Name',
    'erp.field_type': 'Field Type',
    'erp.required': 'Required',
    'erp.add_field': 'Add Field',
    'erp.add_row': 'Add Row',
    'erp.delete_row': 'Delete Row',
    'erp.export_csv': 'Export CSV',
    'erp.export_excel': 'Export Excel',
    'erp.import': 'Import',
    'erp.columns': 'Columns',
    'erp.filters': 'Filters',
    'erp.search': 'Search...',
    'erp.no_data': 'No data yet. Add a row or import from file.',
    'erp.no_fields': 'No fields defined. Add a field to start.',
    'erp.toolbox': 'Field Toolbox',
    'erp.basic_fields': 'Basic Fields',
    'erp.layout_fields': 'Layout Fields',
    'erp.advanced_fields': 'Advanced Fields',
    'erp.filter_panel': 'Filter Panel',
    'erp.add_filter': 'Add Condition',
    'erp.clear_filters': 'Clear All',
    'erp.saved_views': 'Saved Views',
    'erp.save_view': 'Save View',
    'erp.load_view': 'Load View',
    'erp.product.name': 'Product Name',
    'erp.product.desc': 'Description',
    'erp.product.datasource': 'Data Source',
    'erp.product.rules': 'Configuration Rules',
    'erp.product.identity': 'Product Identity',
    'erp.product.save': 'Save into Library',
    'erp.product.pending': 'Pending Configuration',
    'erp.product.image': 'Product Image',
    'erp.rule.add': 'Add Rule',
    'erp.rule.mapping': 'Mapping Rule',
    'erp.rule.logic': 'Logic Rule',
    'erp.rule.delete': 'Delete Rule',
    'erp.naming': 'Naming Rules',
    'erp.naming.preview': 'Preview',
    'erp.naming.builder': 'Rule Builder',
    'erp.naming.library': 'Template Library',
    'erp.quantity': 'Quantity',
    'erp.place_order': 'Place Order',
    'erp.settings.data': 'Data Management',
    'erp.settings.export_config': 'Export Configuration',
    'erp.confirm.delete_product': 'Delete this product?',
    'erp.confirm.delete_dataset': 'Delete this dataset?',
    'erp.confirm.delete_template': 'Delete this template?',
    'erp.confirm.delete_group': 'Delete this folder?',
    'erp.confirm.delete_all': 'Delete all contents',
    'erp.confirm.move_to_root': 'Move to root',
    'erp.toast.saved': 'Saved successfully',
    'erp.toast.deleted': 'Deleted successfully',
    'erp.toast.imported': 'Imported successfully',
    'erp.toast.exported': 'Exported successfully',
    'erp.toast.error': 'An error occurred',
    // Additional ERP UI strings
    'erp.sort_by': 'Sort By',
    'erp.sort.name_asc': 'Name (A-Z)',
    'erp.sort.name_desc': 'Name (Z-A)',
    'erp.sort.date_new': 'Date (Newest)',
    'erp.sort.date_old': 'Date (Oldest)',
    'erp.basic_inputs': 'Basic Inputs',
    'erp.selection': 'Selection',
    'erp.structure': 'Structure',
    'erp.advanced_layout': 'Advanced & Layout',
    'erp.ai_assistant': 'AI Assistant',
    'erp.ai_generate': 'AI Generate',
    'erp.ai_generate_desc': 'From description',
    'erp.ai_logic': 'AI Logic',
    'erp.ai_logic_desc': 'Configure rules',
    'erp.manage_forms': 'Manage Forms',
    'erp.save_as_new': 'Save as New',
    'erp.update_template': 'Update Template',
    'erp.reset_overrides': 'Reset Overrides',
    'erp.rows_affected': 'rows affected',
    'erp.please_select': 'Please select...',
    'erp.enter_value': 'Enter value...',
    'erp.hide': 'Hide',
    'erp.show': 'Show',
    'erp.rename': 'Rename',
    'erp.delete': 'Delete',
    'erp.new_folder': 'New Folder',
    'erp.sort_datasets': 'Sort Datasets',
    'erp.rule_templates': 'Rule Templates',
    'erp.no_logic_templates': 'No logic templates found',
    'erp.no_mapping_templates': 'No mapping templates found',
    // Data Manager Actions
    'erp.select_template': 'Select Template',
    'erp.no_saved_templates': 'No saved templates',
    'erp.manage_library': 'Manage Library',
    'erp.toggle_filters': 'Toggle Filters',
    'erp.mock_data': 'Mock Data',
    'erp.toggle_columns': 'Toggle Columns',
    'erp.columns_title': 'Columns',
    'erp.reset': 'Reset',
    'erp.select_all': 'Select All',
    'erp.close_preview': 'Close Preview',
    'erp.drop_component': 'Drop component here',
    'erp.end_of_form': 'End of Form',
    'erp.datasets': 'Datasets',
    'erp.import_tooltip': 'Import CSV/Excel',
    'erp.export_tooltip': 'Export CSV/Excel',
    'erp.save_options': 'Save Options',
    'erp.save_short': 'Save',
    'erp.save_as': 'Save As',
    'erp.filter_config': 'Filter Configuration',
    'erp.filter_rules': 'Filter Rules',
    'erp.match_all_groups': 'Match All Groups (AND)',
    'erp.match_any_groups': 'Match Any Group (OR)',
    'erp.select_field': 'Select Field...',
    'erp.condition': 'Condition...',
    'erp.max_end': 'Max / End',
    // Library
    'erp.library_desc': 'Manage your collection of saved form templates and schemas.',
    'erp.ai_import': 'AI Import',
    'erp.back_to_builder': 'Back to Builder',
    'erp.create_new_form': 'Create New Form',
    'erp.start_blank': 'Start from a blank canvas',
    'erp.rename_template': 'Rename Template',
    'erp.delete_template': 'Delete Template',
    'erp.no_desc': 'No description provided.',
    'erp.modify_template': 'Modify Template',
    'erp.toast.created_blank': 'Created new blank form',
    'erp.toast.imported_system': 'System Data Imported Successfully',
    'erp.toast.invalid_format': 'Invalid File Format',
    'erp.toast.parse_error': 'Failed to parse import file',
    'erp.settings.system_title': 'System Settings',
    'erp.settings.system_desc': 'Manage global data and export configurations.',
    'erp.settings.backup_desc': 'Backup all products, rules, datasets, and settings to a JSON file.',
    'erp.settings.import_config': 'Import Configuration',
    'erp.settings.restore_desc': 'Restore system state from a backup JSON file.',
    'erp.export_system': 'Export System Data',
    'erp.import_system': 'Import System Data',
    'erp.danger_zone': 'Danger Zone',
    'erp.reset_system': 'Reset System',
    'erp.reset_desc': 'Clear all local data and reset to initial state.',
    'erp.export_json': 'Export JSON',
    'erp.import_json': 'Import JSON',
    'erp.naming.builder_full': 'Naming Rule Builder',
    'erp.tabs.define_product': 'Define Product',
    'erp.tabs.product_library': 'Product Library',
    'erp.tabs.settings': 'Settings',
    'erp.engine_active': 'Engine Active',
    // Product Definition Center
    'erp.product.data_source': 'Data Source',
    'erp.product.studio': 'Product Configurator Studio',
    'erp.product.reset_title': 'Reset Configuration',
    'erp.product.reset_desc': 'Clear all settings and start over?',
    'erp.product.reset_toast': 'Configuration Reset',
    'erp.product.reset_button': 'Reset',
    'erp.product.step_datasource': '1. Data Source',
    'erp.product.step_rule_engine': '2. Rule Engine',
    'erp.product.step_identity': '3. Product Identity',
    'erp.product.label_database': 'Database',
    'erp.product.choose_dataset': 'Choose Dataset...',
    'erp.product.label_filter_presets': 'Filter Presets',
    'erp.product.select_db_first': 'Select a database first...',
    'erp.product.no_views': 'No views found',
    'erp.product.select_ds_first': 'Please select a data source first',
    'erp.product.rule_templates': 'Rule Templates',
    'erp.product.no_templates': 'No logic templates found',
    'erp.product.skipped_dup_rules': 'Skipped duplicate rules',
    'erp.product.added_preset': 'Added {name}',
    'erp.product.delete_preset_title': 'Delete',
    'erp.product.delete_preset_desc': 'Delete "{name}"?',
    'erp.product.placeholder_name': 'e.g. Solar Panel X500',
    'erp.product.label_desc': 'Brief Description',
    'erp.product.placeholder_desc': 'Describe the product context...',
    'erp.product.label_fit': 'Fit:',
    'erp.product.fit_cover': 'Cover',
    'erp.product.fit_contain': 'Contain',
    'erp.product.fit_fill': 'Fill',
    'erp.product.fit_tile': 'Tile',
    'erp.product.placeholder_img_url': 'Image URL...',
    'erp.product.upload': 'Upload',
    'erp.product.no_mapping_templates': 'No mapping templates found',
    'erp.product.active_rules_stack': 'Active Rules Stack',
    'erp.product.source': 'Source',
    'erp.product.target': 'Target',
    'erp.product.when': 'WHEN',
    'erp.product.changes': 'changes',
    'erp.product.update': 'UPDATE',
    'erp.product.pinned': 'Pinned',
    'erp.product.no_mappings': 'No mappings defined',
    'erp.product.more': 'more...',
    'erp.product.value': 'Value',
    'erp.product.result': 'Result',
    'erp.product.more_mappings': 'more mappings...',
    'erp.product.row_pinned': 'Row #{row} Pinned',
    'erp.product.logic_if': 'IF',
    'erp.product.logic_set': 'SET',
    'erp.product.expression': 'EXPRESSION:',
    'erp.product.save_template': 'Save as Template',
    'erp.product.placeholder_template_name': 'Template Name...',
    'erp.product.rule_updated': 'Rule updated successfully',
    'erp.product.click_row_preview': 'Please click a row in the Preview table',
    'erp.product.rule_added': 'Rule added to stack',
    'erp.product.preset_exists': 'Preset name "{name}" already exists',
    'erp.product.preset_saved': 'Preset "{name}" saved to library',
    'erp.product.saved_as_preset': 'Saved as Preset',
    'erp.product.edit_rule': 'Edit Rule',
    'erp.product.delete_rule': 'Delete Rule',
    'erp.confirm.delete_template_title': 'Delete Template',
    'erp.confirm.delete_template_msg': 'Are you sure you want to delete this form template?',
    'erp.confirm.delete_folder_title': 'Delete Folder',
    'erp.confirm.delete_folder_msg': 'Are you sure you want to delete this folder?',
    'erp.confirm.delete_dataset_title': 'Delete Dataset',
    'erp.confirm.delete_dataset_msg': 'Are you sure you want to delete this dataset?',
    'erp.confirm.overwrite_dataset_title': 'Overwrite Dataset',
    'erp.confirm.overwrite_dataset_msg': 'Dataset "{name}" already exists. Overwrite?',
    'erp.toast.template_saved': 'Form saved to library',
    'erp.toast.template_loaded': 'Template loaded: {name}',
    'erp.toast.template_deleted': 'Form template deleted',
    'erp.toast.export_success': 'Export successful!',
    'erp.toast.mock_generated': 'Generated mock record',
    'erp.confirm.delete_group_title': 'Delete Folder',
    'erp.confirm.delete_group_desc': 'You are deleting "{name}". What do you want to do with the datasets inside it?',
    'erp.delete_group.move_root': 'Move to Root',
    'erp.delete_group.move_root_desc': 'Keep datasets, only delete folder',
    'erp.delete_group.delete_all': 'Delete Everything',
    'erp.delete_group.delete_all_desc': 'Delete folder AND all its datasets',
    'erp.export_dialog.title': 'Project Order Info',
    'erp.export_dialog.desc': '',
    'erp.export_dialog.project': 'Project Name',
    'erp.export_dialog.personnel': 'Personnel Name',
    'erp.export_dialog.preview': 'Expected Filename',
    'erp.export_dialog.confirm': 'Confirm Export',
    'erp.rename_dialog.title_dataset': 'Rename Dataset',
    'erp.rename_dialog.title_form': 'Rename Template',
    'erp.rename_dialog.desc_dataset': 'Enter a new name for this dataset.',
    'erp.rename_dialog.desc_form': 'Enter a new name for this form template.',
    'erp.rename_dialog.new_name': 'New Name',
    'erp.ai.processing': 'Processing...',
    'erp.ai.generate_form': 'Generate Form',
    'erp.ai.apply_logic': 'Apply Logic',
    'erp.ai.current_fields': 'Current form has {count} fields: {fields}',
    'erp.form.save_record': 'Save Record',
    'erp.form.submit': 'Submit',
    'erp.toast.cleared_cells': 'Cleared {count} cells',
    'erp.toast.restore_failed': 'Data restore failed. Check console.',
    'erp.toast.data_cleared': 'All data cleared',
    'erp.naming.interactive_mode': 'Complete naming on export',
    'erp.naming.new_variable': 'New List Variable',
    'erp.naming.variable_name': 'Variable Name',
    'erp.naming.add_options': 'Add Options (Values)',
    'erp.naming.type_enter': 'Type and press Enter...',
    'erp.naming.create_variable': 'Create Variable Library Item',
    'erp.naming.realtime_preview': 'Real-time Preview',
    'erp.naming.rule_lib': 'Naming Rule Library',
    'erp.naming.template_name_ph': 'Template Name...',
    'erp.naming.save_current': 'Save Current Rule',
    'erp.naming.toast_saved': 'Rule template saved',
    'erp.naming.no_templates': 'No saved rule templates. Create and save a naming rule first.',
    'erp.naming.default': 'Default',
    'erp.naming.unset_default': 'Unset Default',
    'erp.naming.set_default': 'Set Default',
    'erp.naming.toast_loaded': 'Rule template loaded',
    'erp.naming.load': 'Load',
    'erp.naming.toast_deleted': 'Rule template deleted',
    'erp.naming.separators': 'Separators',
    'erp.naming.space': 'Space',
    'erp.naming.system_vars': 'Auto-fill Components',
    'erp.naming.var_product': 'Product Name',
    'erp.naming.var_project': 'Project Name',
    'erp.naming.var_user': 'Export Person',
    'erp.naming.var_date': 'Export Date',
    'erp.naming.var_qty': 'Order Qty',
    'erp.naming.custom_lists': 'Variable Library',
    'erp.naming.no_custom': 'No variables in library',
    'erp.config.located_row': 'Located Row',
    'erp.config.logic': 'Logic',
    'erp.config.if': 'If',
    'erp.config.set': 'Set',
    'erp.config.quantity': 'Quantity',
    'erp.config.place_order': 'Place Order',
    'erp.toast.order_placed': 'Order Placed & BOM Exported',
    'erp.config.bom_arch': 'BOM Architecture',
    'erp.toast.system_exported': 'System Data Exported Successfully',
    'erp.fill.options': 'Auto Fill Options',
    'erp.fill.copy': 'Copy Cells',
    'erp.fill.series': 'Fill Series',
    'erp.editor.req': 'Req',
    'erp.editor.half': 'Half Width',
    'erp.editor.full': 'Full Width',
    'erp.editor.label': 'Field Label',
    'erp.editor.label_ph': 'Enter label...',
    'erp.editor.var_id': 'Variable ID',
    'erp.editor.var_name': 'Variable Name',
    'erp.editor.var_desc': 'Variable Name for Logic Formulas (Alphanumeric only)',
    'erp.editor.save': 'Save',
    'erp.editor.width': 'Width',
    'erp.editor.config': 'Configuration',
    'erp.editor.required': 'Required',
    'erp.editor.placeholder_ph': 'Placeholder text...',
    'erp.editor.help_ph': 'Help / Hint text...',
    'erp.editor.show_grid': 'Show in Grid',
    'erp.editor.show_batch': 'Show in Batch',
    'erp.editor.options': 'Options',
    'erp.editor.items': 'items',
    'erp.editor.option_ph': 'Option',
    'erp.editor.add_option': 'Add New Option',
    'erp.editor.notice_content_ph': 'Enter notice content...',
    'erp.editor.default_content_ph': 'Enter default content...',
    'erp.logic.engine': 'Logic Engine',
    'erp.logic.visibility': 'Visibility Rule (Show ...)',
    'erp.logic.expression_ph': 'Expression...',
    'erp.logic.calculation': 'Calculated Value (=)',
    'erp.logic.formula_ph': 'Formula...',
    'erp.logic.dynamic_options': 'Dynamic Options Rule',
    'erp.logic.returns_array': 'Returns Array',
    'erp.logic.external_data': 'External Data Logic',
    'erp.logic.simulated_api': 'Simulated API',
    'erp.logic.regex_validation': 'Regex Validation',
    'erp.logic.regex_ph': 'Regex Pattern...',
    'erp.logic.error_msg': 'Error Msg',
    'erp.logic.custom_validation': 'Custom Logic Validation',
    'erp.logic.readonly_rule': 'Read-Only Rule',
    'erp.logic.required_rule': 'Required Rule',
    'erp.logic.disabled_rule': 'Disabled Rule',
    'erp.logic.default_rule': 'Default Value Rule',
    'erp.rule.mapping_tab': 'Mapping Rule',
    'erp.rule.logic_tab': 'Logic Rule',
    'erp.rule.logic_group': 'Conditions Group',
    'erp.rule.current_row': 'Current Row',
    'erp.rule.field_ph': 'Field...',
    'erp.rule.value_ph': 'Value...',
    'erp.rule.add_condition': 'Add Condition',
    'erp.rule.target_field': 'Target Field',
    'erp.rule.select_target_ph': 'Select Target...',
    'erp.rule.set_value': 'Value / Expr',
    'erp.rule.set_value_ph': 'e.g. VIP, 100, {f1} * 2',
    'erp.rule.multi_cascade': 'Multi-Cascade',
    'erp.rule.sync_mode': '🔗 Sync Mode',
    'erp.rule.sync_mode_title': 'Sync Mode: All groups share same option values',
    'erp.rule.independent_mode': '🔓 Independent Mode',
    'erp.rule.independent_mode_title': 'Independent Mode: Each group has independent option values',
    'erp.rule.sync_enabled_msg': '💡 Sync Mode Enabled: Editing any group\'s source value will sync across others',
    'erp.rule.cascade_group_num': 'Group',
    'erp.rule.source_field_ph': 'Source Field...',
    'erp.rule.target_field_ph': 'Target Field...',
    'erp.rule.source_val_ph': 'When value is...',
    'erp.rule.target_val_ph': 'Set to...',
    'erp.rule.add_mapping_val': 'Add Mapping Value',
    'erp.rule.add_cascade_group': 'Add Cascade Group',
    'erp.rule.tab_title': 'Tab Title (Optional)',
    'erp.rule.tab_title_ph': 'Uses description by default...',
    'erp.rule.save_edit': 'Save Changes',
    'erp.rule.apply_stack': 'Apply to Stack',
    // AI Import
    'erp.ai.import_title': 'AI Import',
    'erp.ai.import_desc': 'Generating form from spreadsheet',
    'erp.ai.progress': 'Progress',
    'erp.ai.step1': 'Reading file',
    'erp.ai.step2': 'Extracting structure',
    'erp.ai.step3': 'AI analyzing patterns',
    'erp.ai.step4': 'Generating components',
    'erp.ai.analyzing': 'AI is analyzing data patterns...',
  },
  zh: {
    // Common
    'common.search': '搜索任务、负责人...',
    'common.filter': '所有状态',
    'common.add': '添加',
    'common.delete': '删除',
    'common.cancel': '取消',
    'common.submit': '提交',
    'common.save': '保存',
    'common.edit': '编辑',
    'common.done': '完成',
    'common.close': '关闭',
    'common.note': '备注',
    'common.warn': '警告',
    'common.back': '返回',
    'common.select': '选择',
    'common.create': '创建',
    'common.save_changes': '保存更改',
    'common.confirm': '确认',
    'common.attention': '注意',
    'common.error': '错误',
    // App
    'app.title': 'Gen-项目管理',
    'app.desc': 'AI 驱动的项目管理工具',
    'app.view.dashboard': '项目仪表盘',
    'app.view.projects': '项目',
    'app.view.list': '列表',
    'app.view.board': '看板',
    'app.view.gantt': '甘特图',
    'app.view.calendar': '日历',
    'app.view.meetings': '会议记录',
    'app.view.wiki': '知识库',
    'app.view.goals': '目标 & 战略',
    'app.view.files': '文件中心',
    'app.view.finance': '财务',
    'app.view.issues': '问题跟踪',
    'app.view.risks': '风险',
    'app.view.super_table': '超级数据表',
    'app.export': '导出 CSV',
    'app.team': '团队管理',
    'app.ai_generate': 'AI 生成',
    'app.new_phase': '新阶段',
    'app.no_data': '暂无数据',
    'app.create_phase': '创建阶段',
    'app.gen_ai': '使用 AI 生成',
    'app.switch_lang': 'English',
    'app.project_name_exists': '项目名称已存在，请使用不同的名称',
    // Project Meta
    'project.back': '返回项目库',
    'project.name_label': '项目名称',
    'project.desc_label': '项目描述',
    'project.manager_label': '项目经理',
    'project.created': '创建时间',
    'project.unnamed': '未命名项目',
    'project.no_desc': '暂无描述',
    'project.delete_confirm_title': '删除项目？',
    'project.delete_confirm_msg': '这将永久删除该项目及其所有关联任务、会议和文档。',
    'project.code': '代号',
    'project.budget_total': '总预算',
    'project.settings_title': '项目设置',
    // Dashboard
    'dash.total_tasks': '总任务数',
    'dash.completion_rate': '完成率',
    'dash.pending_items': '待办事项',
    'dash.delayed': '延期/风险',
    'dash.team_workload': '团队工作量',
    'dash.status_dist': '任务状态分布',
    'dash.upcoming': '即将到期',
    'dash.no_upcoming': '近期无截止任务',
    'dash.recent_activity': '最近动态',
    'dash.phase_progress': '阶段进度',
    // ProjectTable
    'table.phase_tasks': '个任务',
    'table.add_task': '添加任务',
    'table.task_name': '任务名称',
    'table.description': '任务描述',
    'table.deliverables': '交付物',
    'table.wait_for': '等待: ',
    'table.status': '状态',
    'table.priority': '优先级',
    'table.schedule': '排期',
    'table.assigned_to': '负责人',
    'table.overdue': '逾期',
    'table.days': '天',
    'table.set_duration': '设置工期',
    'table.start_date': '开始日期',
    'table.end_date': '结束日期',
    'table.link_name': '名称 (如 Figma)',
    'table.link_url': '链接 (https://...)',
    'table.add_link': '添加链接',
    'table.attachments': '附件',
    'table.no_links': '暂无链接',
    'table.wait_tasks': '等待任务:',
    'table.delete_task_confirm': '确定删除此任务吗？',
    'table.serial_number': '序号',
    // Status
    'status.Pending': '待办',
    'status.In Progress': '进行中',
    'status.Completed': '已完成',
    'status.Delayed': '延期',
    'status.Open': '待处理',
    'status.Planning': '方案制定中',
    'status.Closed': '已关闭',
    'status.All': '所有状态',
    // Priority
    'priority.Low': '低',
    'priority.Med': '中',
    'priority.High': '高',
    // AI Generator
    'ai.title': 'AI 项目架构师',
    'ai.subtitle': "描述您想构建的内容，我将为您创建结构化的计划。",
    'ai.subtitle.settings': '配置您的 AI 提供商',
    'ai.placeholder': '例如：组织一次技术会议...',
    'ai.btn.generate': '生成计划',
    'ai.btn.generating': '生成中...',
    'ai.btn.import': '导入项目',
    'ai.preview': '预览生成计划',
    'ai.start_over': '重新开始',
    'ai.settings': '设置',
    'ai.provider': 'AI 提供商',
    'ai.api_key': 'API 密钥',
    'ai.model': '模型名称',
    'ai.base_url': 'Base URL',
    'ai.cancel': '取消',
    'ai.save_config': '保存配置',
    'ai.thinking': '思考中...',
    'ai.phase': '阶段',
    'ai.target_project': '所属项目',
    'ai.structure_type': '生成结构',
    'ai.structure.full': '完整项目 (多个阶段)',
    'ai.structure.single': '单个阶段 (任务列表)',
    'ai.select_project': '选择一个项目...',
    // Kanban
    'kanban.move_to': '移动到:',
    'kanban.drop': '拖拽任务到此处',
    'kanban.no_phases': '暂无阶段',
    // Team
    'team.title': '团队目录',
    'team.subtitle': '管理团队，查看工作量和任务分配。',
    'team.add_new': '添加成员',
    'team.current': '当前成员',
    'team.add_btn': '添加到团队',
    'team.name_placeholder': '姓名 (如 张三)',
    'team.role_placeholder': '角色 (如 开发人员)',
    'team.total': '成员总数',
    'team.skills': '技能 (逗号分隔)',
    'team.email': '邮箱',
    'team.department': '部门',
    'team.workload': '工作量',
    'team.active_tasks': '活跃任务',
    'team.required_error': '姓名和角色为必填项',
    'team.added': '成员已添加',
    'team.updated': '成员信息已更新',
    'team.removed': '成员已移除',
    'team.remove_title': '移除团队成员？',
    'team.remove_warning': '警告：该成员仍有活跃任务。移除后这些任务将变为未分配状态。',
    'team.remove_confirm': '确定要移除该成员吗？',
    'team.total_suffix': '总数',
    // AI Assistant
    'audit.btn': 'AI 审计',
    'audit.title': '项目 AI 分析师',
    'audit.intro': '我可以分析该项目的进度风险和优化机会。',
    'audit.start': '开始分析',
    'audit.analyzing': '正在分析进度数据...',
    'audit.reanalyze': '重新分析',
    // Task Detail
    'task.detail': '任务详情',
    'task.checklist': '检查清单',
    'task.comments': '评论',
    'task.activity': '动态与评论',
    'task.ai_breakdown': 'AI 拆解',
    'task.add_item': '添加子项',
    'task.add_comment': '发布评论',
    'task.enter_comment': '写下评论...',
    'task.enter_item': '新检查项...',
    'task.no_comments': '暂无评论',
    'task.no_checklist': '暂无检查项',
    'task.linked_docs': '知识库关联',
    'task.link_doc_placeholder': '搜索文档以关联...',
    'task.link_goal': '关联目标',
    'task.select_goal': '选择一个战略目标...',
    'task.high_priority': '高优先级',
    'task.add_desc': '添加更详细的描述...',
    'task.commenting_as': '评论身份:',
    'task.select_user': '选择用户',
    'task.phase': '阶段',
    'task.assignee': '负责人',
    'task.assets': '资产',
    'task.add_asset': '添加链接或文档',
    'task.search_docs': '搜索文档...',
    'task.no_docs': '未找到文档。',
    'task.ai_checklist_success': '检查项已生成！',
    'task.ai_checklist_fail': 'AI 拆解失败',
    'task.comment_deleted': '评论已删除',
    'task.save_changes': '保存更改',
    // Meeting
    'mtg.title': '会议记录',
    'mtg.add': '新建会议',
    'mtg.type': '会议类型',
    'mtg.date': '日期',
    'mtg.attendees': '参会人',
    'mtg.minutes': '会议纪要',
    'mtg.action_items': '行动项 (Action Items)',
    'mtg.convert_task': '选中转任务',
    'mtg.convert_tip': '在编辑器中选中文字以创建任务',
    'mtg.linked_tasks': '关联任务',
    'mtg.templates': '模板',
    'mtg.timer': '计时器',
    'mtg.status_planned': '计划中',
    'mtg.status_in_progress': '进行中',
    'mtg.status_completed': '已结束',
    'mtg.tpl_standup': '每日站会',
    'mtg.tpl_review': '需求评审',
    'mtg.tpl_retro': '复盘回顾',
    'mtg.ai_summary': 'AI 总结',
    'mtg.generating_summary': '正在生成总结...',
    'mtg.select_phase_title': '添加任务到阶段',
    'mtg.select_phase_desc': '选择要将任务添加到哪个阶段：',
    'mtg.new_phase_name': '新阶段名称',
    'mtg.rec_started': '录音已开始...',
    'mtg.rec_not_supported': '不支持音频录制，请上传文件。',
    'mtg.mic_not_found': '未找到麦克风，请使用上传功能。',
    'mtg.mic_denied': '麦克风权限被拒绝，请检查设置。',
    'mtg.rec_error': '录音启动失败',
    'mtg.file_too_large': '文件过大 (最大 20MB)，请上传较小的文件。',
    'mtg.transcribe_success': '音频转录成功！',
    'mtg.transcribe_fail': '转录失败',
    'mtg.minutes_success': '会议纪要转录成功！',
    'mtg.summary_success': '总结和行动项已生成',
    'mtg.summary_fail': '生成总结失败',
    'mtg.overwrite_confirm': '覆盖当前内容？',
    'mtg.select_text_warn': '请先选择文本',
    'mtg.task_created': '已从选中内容创建任务',
    'mtg.title_placeholder': '会议标题',
    'mtg.no_phases': '无现有阶段',
    // Wiki
    'wiki.title': '知识库',
    'wiki.new_page': '新建页面',
    'wiki.search': '搜索文档...',
    'wiki.untitled': '无标题页面',
    'wiki.external': '外部链接',
    'wiki.type_slash': "输入 '/' 唤起命令",
    'wiki.linked_tasks': '反向关联任务',
    'wiki.html_block': '智能 HTML',
    'wiki.html_placeholder': '描述你想要的 UI (例如：三栏定价表，包含价格和按钮)',
    'wiki.html_generate': '生成 UI',
    'wiki.basic_blocks': '基础块',
    'wiki.turn_into': '转换为',
    'wiki.click_to_add': '点击添加内容',
    'wiki.last_edited': '最后编辑',
    'wiki.outline': '大纲',
    'wiki.no_headings': '暂无标题。',
    'wiki.no_linked': '此页面未关联任务。',
    'wiki.untitled_page': '无标题页面',
    'wiki.change_cover': '更换封面',
    'wiki.block_text': '文本',
    'wiki.block_h1': '标题 1',
    'wiki.block_h2': '标题 2',
    'wiki.block_h3': '标题 3',
    'wiki.block_bullet': '无序列表',
    'wiki.block_todo': '待办列表',
    'wiki.block_quote': '引用',
    'wiki.block_code': '代码',
    'wiki.block_image': '图片',
    'wiki.block_html': '智能 HTML',
    'wiki.block_task': '关联任务',
    'wiki.block_doc': '页面链接',
    'wiki.delete_doc_title': '删除文档？',
    'wiki.delete_doc_msg': '确定要删除此文档吗？此操作无法撤销。',
    'wiki.img_placeholder': '粘贴图片 URL 并回车...',
    'wiki.quote_placeholder': '空引用',
    'wiki.code_placeholder': '// 在此输入代码',
    'wiki.list_placeholder': '列表项',
    'wiki.todo_placeholder': '待办项',
    'wiki.select_placeholder': '选择一个页面开始写作',
    'wiki.task_not_found': '任务未找到或已删除',
    'wiki.doc_deleted': '文档已删除',
    'wiki.ui_gen_success': 'UI 已生成',
    'wiki.ui_gen_fail': '生成失败',
    'wiki.ui_preview_placeholder': 'UI 预览将在此显示。',
    'wiki.block_text_desc': '开始输入纯文本。',
    // Goals
    'goals.title': '目标与 OKR',
    'goals.add': '新目标',
    'goals.progress': '进度',
    'goals.linked_tasks': '关联任务数',
    'goals.status_ontrack': '正常',
    'goals.status_atrisk': '有风险',
    'goals.status_offtrack': '偏离',
    'goals.status_completed': '已完成',
    'goals.auto_progress': '基于关联任务自动计算',
    'goals.subtitle': '定义战略目标并跟踪关键结果。',
    'goals.title_placeholder': '目标标题 (例如：Q4 发布 MVP)',
    'goals.desc_placeholder': '描述 / 关键结果...',
    'goals.create': '创建目标',
    'goals.no_goals': '暂无目标。请先添加战略目标。',
    'goals.created': '新目标已创建',
    'goals.owner_placeholder': '负责人姓名',
    'goals.due_prefix': '截止:',
    // Files
    'files.title': '文件资源中心',
    'files.upload': '上传文件',
    'files.filter_all': '全部文件',
    'files.filter_img': '图片',
    'files.filter_doc': '文档',
    'files.source': '来源',
    'files.subtitle': '所有项目资产和链接的中央存储库。',
    'files.search_placeholder': '搜索文件...',
    'files.no_results': '未找到匹配的文件。',
    'files.unknown_user': '未知用户',
    // Notifications
    'notif.title': '通知',
    'notif.mark_read': '全部已读',
    'notif.empty': '暂无新通知',
    // Settings
    'settings.profile': '个人资料',
    'settings.appearance': '外观与密度',
    'settings.language': '界面语言',
    'settings.save': '保存偏好设置',
    'settings.ai_config': 'AI 配置',
    'settings.ai_desc': '在此配置全局 AI 设置。这些密钥将用于 AI 助手、项目生成器和任务拆解功能。',
    'settings.data': '数据管理',
    'settings.backup': '备份与恢复',
    'settings.export': '导出数据',
    'settings.import': '导入数据',
    'settings.danger': '危险区域',
    'settings.reset_desc': '重置将清除数据库中的所有数据。请确保在继续之前已导出备份。',
    'settings.reset_btn': '重置所有应用数据',
    'settings.shortcuts': '键盘快捷键',
    'settings.about': '关于软件',
    'settings.workspace': '工作区配置',
    'settings.display_name': '显示名称',
    'settings.role_title': '角色 / 职位',
    'settings.version': 'v1.3.0 (IndexedDB)',
    'settings.app_desc': '专为速度和简洁而设计的现代化 AI 项目管理工作区。',
    'settings.meta_version': '版本',
    'settings.meta_license': '许可',
    'settings.meta_stack': '技术栈',
    'settings.meta_ai_model': 'AI 模型',
    'settings.reset_title': '重置所有数据？',
    'settings.reset_confirm': '全部重置',
    'settings.pref_updated': '偏好设置已更新',
    'settings.ai_saved': 'AI 配置已保存',
    'settings.export_success': '数据导出成功',
    'settings.export_fail': '导出失败',
    'settings.import_title': '导入数据？',
    'settings.import_desc': '这将使用备份文件覆盖当前数据。现有项目将被替换。',
    'settings.import_confirm': '覆盖并导入',
    'settings.invalid_backup': '无效的备份文件',
    // Finance
    'fin.budget': '预算与财务',
    'fin.total_budget': '总预算',
    'fin.total_spent': '总支出',
    'fin.remaining': '剩余预算',
    'fin.burn': '预算消耗',
    'fin.used': '已用',
    'fin.log': '支出记录',
    'fin.manage_cats': '管理分类',
    'fin.log_btn': '记录支出',
    'fin.desc': '描述',
    'fin.amount': '金额',
    'fin.no_expenses': '暂无支出记录。',
    'fin.cat_exists': '分类已存在',
    'fin.cat_added': '分类已添加',
    'fin.cat_removed': '分类已移除',
    'fin.expense_logged': '支出已记录',
    'fin.budget_updated': '预算已更新',
    'fin.new_cat_placeholder': '新分类...',
    // Risks
    'risk.register': '风险登记册',
    'risk.subtitle': '识别、评估和减轻项目风险。',
    'risk.add': '添加风险',
    'risk.mitigation': '缓解计划',
    'risk.probability': '可能性',
    'risk.impact': '影响',
    'risk.save': '保存风险',
    'risk.issue': '风险/问题',
    'risk.level': '等级',
    'risk.no_risks': '暂无风险记录。保持安全！',
    'risk.ai_detect': 'AI 检测',
    'risk.prob_short': '概率',
    'risk.impact_short': '影响',
    'risk.desc_placeholder': '例如：服务器宕机',
    'risk.mitigation_placeholder': '例如：建立备份区域',
    'risk.ai_success': 'AI 识别到的风险',
    'risk.ai_fail': '生成风险失败',
    // Portfolio
    'port.title': '全局概览',
    'port.subtitle': '活跃项目的高级概览。',
    'port.active': '活跃项目',
    'port.global_completion': '全局完成率',
    'port.risk_projects': '风险项目',
    'port.open_tasks': '待办任务',
    'port.timeline': '项目时间轴与健康度',
    'port.heatmap': '资源热力图',
    'port.no_assignments': '无活跃分配。',
    'port.optimal': '最佳',
    'port.busy': '繁忙',
    'port.overload': '过载',
    'port.manager_prefix': '经理:',
    'port.risk_badge': '风险',
    // Gantt
    'gantt.task_list': '任务列表',
    'gantt.today': '今天',
    'gantt.delete_dep_msg': '删除依赖关系？',
    'gantt.dep_removed': '依赖关系已移除',
    'gantt.dep_created': '依赖关系已创建',
    // Calendar
    'cal.today': '今天',
    // Chat
    'chat.title': '项目助手',
    'chat.powered': '由 Gemini 驱动',
    'chat.clear': '清除历史',
    'chat.placeholder': '询问关于项目的问题...',
    'chat.intro': '你好！我是 **{projectName}** 的 AI 助手。你可以问我关于任务进度、团队分工或风险分析的问题。',
    'chat.cleared': '已清空上下文。你可以重新开始提问。',
    'chat.error': '聊天错误',
    'chat.error_response': '抱歉，处理您的请求时遇到错误。',
    // Issue Tracker
    'issue.title': '问题跟踪器',
    'issue.subtitle': '跟踪和管理项目问题及异常',
    'issue.import_data': '导入数据',
    'issue.report': '报告问题',
    'issue.search_placeholder': '搜索问题...',
    'issue.filter.all_status': '所有状态',
    'issue.filter.all_projects': '所有项目',
    'issue.table.id': '编号',
    'issue.table.date': '日期',
    'issue.table.project': '项目',
    'issue.table.description': '描述',
    'issue.table.assets': '资产',
    'issue.table.status': '状态',
    'issue.table.responsible': '负责人',
    'issue.table.discovery': '发现日期',
    'issue.table.resolution': '解决日期',
    'issue.table.actions': '操作',
    'issue.no_issues': '未找到符合条件的问题。',
    'issue.import.title': '导入问题',
    'issue.import.desc': '在此粘贴您的 Excel/CSV 数据。请确保列匹配：编号、日期、项目、系统、大类、问题发生阶段、子类、报告人、跟踪人、描述、附件、根本原因、负责人、解决方案、状态。',
    'issue.import.placeholder': '在此粘贴制表符分隔的数据...',
    'issue.import.btn': '导入问题',
    'issue.import.error': '未找到可导入的有效问题。请确保数据以制表符分隔。',
    'issue.import.success': '问题导入成功',
    'issue.delete_title': '删除问题',
    'issue.delete_confirm': '确定要删除此问题吗？',
    'issue.delete_success': '问题删除成功',
    'issue.linked_docs': '关联文档',
    'issue.view_images': '查看图片',
    'issue.view_linked_docs': '查看关联文档',
    // Issue Modal
    'issue.modal.edit_title': '编辑问题',
    'issue.modal.new_title': '报告新问题',
    'issue.modal.id_prefix': '编号: ',
    'issue.modal.new_desc': '记录新的异常或缺陷',
    'issue.modal.project': '项目',
    'issue.modal.select_project': '选择项目',
    'issue.modal.category': '问题发生阶段',
    'issue.modal.category_placeholder': '例如：开发阶段、测试阶段',
    'issue.modal.description': '描述',
    'issue.modal.description_placeholder': '详细描述问题...',
    'issue.modal.ai_analyze': '智能分析',
    'issue.modal.ai_analyzing': '分析中...',
    'issue.modal.ai_config_missing': 'AI配置缺失，请检查设置。',
    'issue.modal.ai_error': '智能分析失败，请检查API Key。',
    'issue.modal.attachments': '附件',
    'issue.modal.add_image': '添加图片',
    'issue.modal.upload_placeholder': '点击上传图片',
    'issue.modal.root_cause': '根本原因分析',
    'issue.modal.root_cause_placeholder': '为什么会发生这种情况？',
    'issue.modal.temp_solution': '临时解决方案',
    'issue.modal.temp_solution_placeholder': '立即缓解措施...',
    'issue.modal.root_solution': '根本解决措施',
    'issue.modal.root_solution_placeholder': '彻底解决问题的方案，防止再次发生...',
    'issue.modal.status': '状态',
    'issue.modal.date_reported': '报告日期',
    'issue.modal.discovery_date': '发现日期',
    'issue.modal.resolution_date': '解决日期',
    'issue.modal.people': '人员',
    'issue.modal.reporter': '报告人',
    'issue.modal.reporter_placeholder': '报告人姓名',
    'issue.modal.responsible': '负责人',
    'issue.modal.responsible_placeholder': '负责人姓名',
    'issue.modal.tracker': '跟踪人',
    'issue.modal.tracker_placeholder': '跟踪人姓名',
    'issue.modal.device_info': '设备信息',
    'issue.modal.device_category': '系统',
    'issue.modal.device_category_placeholder': '例如：控制系统',
    'issue.modal.device_type': '大类',
    'issue.modal.device_type_placeholder': '例如：硬件',
    'issue.modal.source': '子类',
    'issue.modal.source_placeholder': '例如：传感器',

    'issue.modal.linked_docs': '关联文档',
    'issue.modal.no_docs': '此项目中无文档。',
    'issue.modal.save': '保存问题',
    'issue.modal.file_too_large': '文件过大（最大 5MB）',
    'issue.modal.desc_required': '描述为必填项',
    'issue.modal.tag_manager_title': '标签库管理',
    'issue.modal.tag_manager_desc': '管理您的问题自定义标签',
    'issue.modal.add_tag_placeholder': '添加新标签...',
    'issue.modal.no_tags_in_cat': '该分类下暂无标签。',
    'issue.modal.tags_found': '发现 {n} 个未保存标签',
    'issue.modal.tags_found_desc': '存在于问题中但未加入标签库。',
    'issue.modal.import_tags': '全部导入',
    'issue.modal.group_basic': '基本信息',
    'issue.modal.group_device': '设备信息',
    // App Messages
    'app.loading_title': '正在加载 Gen-PM',
    'app.loading_desc': '正在初始化数据库...',
    'app.refreshed': '界面已刷新',
    'app.load_error': '加载数据出错',
    'app.issue_reported': '问题报告成功',
    'app.issue_updated': '问题已更新',
    'app.issue_deleted': '问题已删除',
    'app.issues_imported': '已导入问题',
    'app.project_created': '新项目已创建',
    'app.project_deleted': '项目已删除',
    'app.meeting_deleted': '会议已删除',
    'app.event_updated': '日程更新成功',
    'app.event_created': '日程创建成功',
    'app.event_deleted': '日程已删除',
    'app.sync_success': '同步成功',
    'app.sync_fail': '同步失败，请检查网络连接。',
    'app.workspace': '工作区',
    'app.quick_sync': '快速同步到云端',
    'app.search_placeholder': '搜索...',
    'app.delete_meeting_confirm': '确定要删除此会议吗？此操作无法撤销。',
    // Kanban
    'kanban.unassigned': '未分配',
    // SuperTable / ERP
    'erp.title': '超级表格',
    'erp.subtitle': '数据管理中心',
    'erp.tab.data': '数据',
    'erp.tab.builder': '构建器',
    'erp.tab.library': '模板库',
    'erp.tab.product_center': '产品中心',
    'erp.tab.guide': '使用指南',
    'erp.sub.config': '定义产品',
    'erp.sub.library': '产品库',
    'erp.sub.settings': '设置',
    'erp.view.table': '表格视图',
    'erp.view.preview': '预览',
    'erp.view.batch': '批量录入',
    'erp.my_data': '我的数据',
    'erp.add_dataset': '新建数据集',
    'erp.add_folder': '新建文件夹',
    'erp.save_dataset': '保存数据集',
    'erp.new_dataset': '新建数据集',
    'erp.form_templates': '表单模板',
    'erp.quick_start': '快速开始',
    'erp.new_template': '新建模板',
    'erp.save_template': '另存为模板',
    'erp.load_template': '加载模板',
    'erp.untitled': '无标题',
    'erp.field_name': '字段名称',
    'erp.field_type': '字段类型',
    'erp.required': '必填',
    'erp.add_field': '添加字段',
    'erp.add_row': '添加行',
    'erp.delete_row': '删除行',
    'erp.export_csv': '导出 CSV',
    'erp.export_excel': '导出 Excel',
    'erp.import': '导入',
    'erp.columns': '列管理',
    'erp.filters': '筛选',
    'erp.search': '搜索...',
    'erp.no_data': '暂无数据，请添加行或从文件导入。',
    'erp.no_fields': '暂无字段，请先添加字段。',
    'erp.toolbox': '字段工具箱',
    'erp.basic_fields': '基础字段',
    'erp.layout_fields': '布局字段',
    'erp.advanced_fields': '高级字段',
    'erp.filter_panel': '筛选面板',
    'erp.add_filter': '添加条件',
    'erp.clear_filters': '清空全部',
    'erp.saved_views': '已保存视图',
    'erp.save_view': '保存视图',
    'erp.load_view': '加载视图',
    'erp.product.name': '产品名称',
    'erp.product.desc': '描述',
    'erp.product.datasource': '数据源',
    'erp.product.rules': '配置规则',
    'erp.product.identity': '产品标识',
    'erp.product.save': '保存到产品库',
    'erp.product.pending': '配置中',
    'erp.product.image': '产品图片',
    'erp.rule.add': '添加规则',
    'erp.rule.mapping': '映射规则',
    'erp.rule.logic': '逻辑规则',
    'erp.rule.delete': '删除规则',
    'erp.naming': '命名规则',
    'erp.naming.preview': '预览',
    'erp.naming.builder': '规则构建器',
    'erp.naming.library': '模板库',
    'erp.quantity': '数量',
    'erp.place_order': '批量下单',
    'erp.settings.data': '数据管理',
    'erp.settings.export_config': '导出配置',
    'erp.confirm.delete_product': '确定删除此产品？',
    'erp.confirm.delete_dataset': '确定删除此数据集？',
    'erp.confirm.delete_template': '确定删除此模板？',
    'erp.confirm.delete_group': '确定删除此文件夹？',
    'erp.confirm.delete_all': '删除所有内容',
    'erp.confirm.move_to_root': '移动至根目录',
    'erp.toast.saved': '保存成功',
    'erp.toast.deleted': '删除成功',
    'erp.toast.imported': '导入成功',
    'erp.toast.exported': '导出成功',
    'erp.toast.error': '发生错误',
    // Additional ERP UI strings
    'erp.sort_by': '排序方式',
    'erp.sort.name_asc': '名称 (A-Z)',
    'erp.sort.name_desc': '名称 (Z-A)',
    'erp.sort.date_new': '日期 (最新)',
    'erp.sort.date_old': '日期 (最旧)',
    'erp.basic_inputs': '基础输入',
    'erp.selection': '选择器',
    'erp.structure': '布局结构',
    'erp.advanced_layout': '高级布局',
    'erp.ai_assistant': 'AI 助手',
    'erp.ai_generate': 'AI 生成',
    'erp.ai_generate_desc': '从描述生成',
    'erp.ai_logic': 'AI 逻辑',
    'erp.ai_logic_desc': '配置规则',
    'erp.manage_forms': '管理表单',
    'erp.save_as_new': '另存为新建',
    'erp.update_template': '更新模板',
    'erp.reset_overrides': '重置覆盖',
    'erp.rows_affected': '行受影响',
    'erp.please_select': '请选择...',
    'erp.enter_value': '请输入值...',
    'erp.hide': '隐藏',
    'erp.show': '显示',
    'erp.rename': '重命名',
    'erp.delete': '删除',
    'erp.new_folder': '新建文件夹',
    'erp.sort_datasets': '排序数据集',
    'erp.rule_templates': '规则模板',
    'erp.no_logic_templates': '暂无逻辑模板',
    'erp.no_mapping_templates': '暂无映射模板',
    // Data Manager Actions
    'erp.select_template': '选择模板',
    'erp.no_saved_templates': '暂无已保存模板',
    'erp.manage_library': '管理模板库',
    'erp.toggle_filters': '切换筛选栏',
    'erp.mock_data': '生成模拟数据',
    'erp.toggle_columns': '切换列显示',
    'erp.columns_title': '列',
    'erp.reset': '重置',
    'erp.select_all': '全选',
    'erp.close_preview': '关闭预览',
    'erp.drop_component': '拖放组件至此',
    'erp.end_of_form': '表单结束',
    'erp.datasets': '数据集',
    'erp.import_tooltip': '导入 CSV/Excel',
    'erp.export_tooltip': '导出 CSV/Excel',
    'erp.save_options': '保存选项',
    'erp.save_short': '保存',
    'erp.save_as': '另存为',
    'erp.filter_config': '筛选配置',
    'erp.filter_rules': '筛选规则',
    'erp.match_all_groups': '满足所有组 (AND)',
    'erp.match_any_groups': '满足任一组 (OR)',
    'erp.select_field': '选择字段...',
    'erp.condition': '条件...',
    'erp.max_end': '最大值 / 结束',
    // Library
    'erp.library_desc': '管理已保存的表单模板和架构。',
    'erp.ai_import': 'AI 导入',
    'erp.back_to_builder': '返回构建器',
    'erp.create_new_form': '创建新表单',
    'erp.start_blank': '从空白画布开始',
    'erp.rename_template': '重命名模板',
    'erp.delete_template': '删除模板',
    'erp.no_desc': '无描述。',
    'erp.modify_template': '修改模板',
    'erp.toast.created_blank': '已创建空白表单',
    'erp.toast.imported_system': '系统数据导入成功',
    'erp.toast.invalid_format': '无效的文件格式',
    'erp.toast.parse_error': '解析导入文件失败',
    'erp.settings.system_title': '系统设置',
    'erp.settings.system_desc': '管理全局数据和导出配置。',
    'erp.settings.backup_desc': '将所有产品、规则、数据集和设置备份为 JSON 文件。',
    'erp.settings.import_config': '导入配置',
    'erp.settings.restore_desc': '从备份 JSON 文件恢复系统状态。',
    'erp.export_system': '导出系统数据',
    'erp.import_system': '导入系统数据',
    'erp.danger_zone': '危险区域',
    'erp.reset_system': '重置系统',
    'erp.reset_desc': '清除所有本地数据并重置为初始状态。',
    'erp.export_json': '导出 JSON',
    'erp.import_json': '导入 JSON',
    'erp.naming.builder_full': '命名规则生成器',
    'erp.tabs.define_product': '定义产品',
    'erp.tabs.product_library': '产品库',
    'erp.tabs.settings': '设置',
    'erp.engine_active': '引擎激活',
    // Product Definition Center
    'erp.product.data_source': '数据源',
    'erp.product.studio': '产品配置工作室',
    'erp.product.reset_title': '重置配置',
    'erp.product.reset_desc': '清除所有设置并重新开始？',
    'erp.product.reset_toast': '配置已重置',
    'erp.product.reset_button': '重置',
    'erp.product.step_datasource': '1. 数据源',
    'erp.product.step_rule_engine': '2. 规则引擎',
    'erp.product.step_identity': '3. 产品标识',
    'erp.product.label_database': '数据库',
    'erp.product.choose_dataset': '选择数据集...',
    'erp.product.label_filter_presets': '过滤预设',
    'erp.product.select_db_first': '请先选择数据库...',
    'erp.product.no_views': '未找到视图',
    'erp.product.select_ds_first': '请先选择数据源',
    'erp.product.rule_templates': '规则模板',
    'erp.product.no_templates': '未找到逻辑模板',
    'erp.product.skipped_dup_rules': '已跳过重复规则',
    'erp.product.added_preset': '已添加 {name}',
    'erp.product.delete_preset_title': '删除',
    'erp.product.delete_preset_desc': '确定删除 "{name}"？',
    'erp.product.placeholder_name': '例如：太阳能面板 X500',
    'erp.product.label_desc': '简要描述',
    'erp.product.placeholder_desc': '描述产品背景...',
    'erp.product.label_fit': '适应:',
    'erp.product.fit_cover': '填充',
    'erp.product.fit_contain': '合适',
    'erp.product.fit_fill': '拉伸',
    'erp.product.fit_tile': '平铺',
    'erp.product.placeholder_img_url': '图片链接...',
    'erp.product.upload': '上传',
    'erp.product.no_mapping_templates': '未找到映射模板',
    'erp.product.active_rules_stack': '活动规则堆栈',
    'erp.product.source': '来源',
    'erp.product.target': '目标',
    'erp.product.when': '当',
    'erp.product.changes': '变更',
    'erp.product.update': '更新',
    'erp.product.pinned': '固定',
    'erp.product.no_mappings': '未定义映射',
    'erp.product.more': '更多...',
    'erp.product.value': '值',
    'erp.product.result': '结果',
    'erp.product.more_mappings': '更多映射...',
    'erp.product.row_pinned': '行 #{row} 已固定',
    'erp.product.logic_if': '如果',
    'erp.product.logic_set': '设置',
    'erp.product.expression': '表达式:',
    'erp.product.save_template': '另存为模板',
    'erp.product.placeholder_template_name': '模板名称...',
    'erp.product.rule_updated': '规则更新成功',
    'erp.product.click_row_preview': '请点击预览表中的一行',
    'erp.product.rule_added': '规则已添加到堆栈',
    'erp.product.preset_exists': '预设名称 "{name}" 已存在',
    'erp.product.preset_saved': '预设 "{name}" 已保存到库',
    'erp.product.saved_as_preset': '已保存为预设',
    'erp.product.edit_rule': '编辑规则',
    'erp.product.delete_rule': '删除规则',
    'erp.confirm.delete_template_title': '删除模板',
    'erp.confirm.delete_template_msg': '您确定要删除此表单模板吗？',
    'erp.confirm.delete_folder_title': '删除文件夹',
    'erp.confirm.delete_folder_msg': '您确定要删除此文件夹吗？',
    'erp.confirm.delete_dataset_title': '删除数据集',
    'erp.confirm.delete_dataset_msg': '您确定要删除此数据集吗？',
    'erp.confirm.overwrite_dataset_title': '覆盖数据集',
    'erp.confirm.overwrite_dataset_msg': '数据集 "{name}" 已存在。是否覆盖？',
    'erp.toast.template_saved': '表单已保存到库',
    'erp.toast.template_loaded': '模板已加载: {name}',
    'erp.toast.template_deleted': '表单模板已删除',
    'erp.toast.export_success': '导出成功！',
    'erp.toast.mock_generated': '已生成模拟记录',
    'erp.confirm.delete_group_title': '删除文件夹',
    'erp.confirm.delete_group_desc': '您正在删除 "{name}"。您想如何处理其中的数据集？',
    'erp.delete_group.move_root': '移至根目录',
    'erp.delete_group.move_root_desc': '保留数据集，仅删除文件夹',
    'erp.delete_group.delete_all': '删除所有内容',
    'erp.delete_group.delete_all_desc': '删除文件夹及其所有数据集',
    'erp.export_dialog.title': '项目下单信息',
    'erp.export_dialog.desc': '',
    'erp.export_dialog.project': '项目名称',
    'erp.export_dialog.personnel': '人员名称',
    'erp.export_dialog.preview': '预计文件名',
    'erp.export_dialog.confirm': '确定导出',
    'erp.rename_dialog.title_dataset': '重命名数据集',
    'erp.rename_dialog.title_form': '重命名模板',
    'erp.rename_dialog.desc_dataset': '为此数据集输入新名称。',
    'erp.rename_dialog.desc_form': '为此表单模板输入新名称。',
    'erp.rename_dialog.new_name': '新名称',
    'erp.ai.processing': '处理中...',
    'erp.ai.generate_form': '生成表单',
    'erp.ai.apply_logic': '应用逻辑',
    'erp.ai.current_fields': '当前表单有 {count} 个字段: {fields}',
    'erp.form.save_record': '保存记录',
    'erp.form.submit': '提交',
    'erp.toast.cleared_cells': '已清除 {count} 个单元格',
    'erp.toast.restore_failed': '数据恢复失败。请检查控制台。',
    'erp.toast.data_cleared': '所有数据已清除',
    'erp.naming.interactive_mode': '导出时完善命名',
    'erp.naming.new_variable': '新建列表变量',
    'erp.naming.variable_name': '变量名称',
    'erp.naming.add_options': '添加选项 (值)',
    'erp.naming.type_enter': '输入并回车...',
    'erp.naming.create_variable': '创建变量库项目',
    'erp.naming.realtime_preview': '实时预览',
    'erp.naming.rule_lib': '命名规则库',
    'erp.naming.template_name_ph': '模板名称...',
    'erp.naming.save_current': '保存当前规则',
    'erp.naming.toast_saved': '规则模板已保存',
    'erp.naming.no_templates': '暂无保存的规则模板，请先创建命名规则后保存',
    'erp.naming.default': '默认',
    'erp.naming.unset_default': '取消默认',
    'erp.naming.set_default': '设为默认',
    'erp.naming.toast_loaded': '已加载规则模板',
    'erp.naming.load': '加载',
    'erp.naming.toast_deleted': '规则模板已删除',
    'erp.naming.separators': '分隔符',
    'erp.naming.space': '空格',
    'erp.naming.system_vars': '自动填充组件',
    'erp.naming.var_product': '产品名称',
    'erp.naming.var_project': '项目名称',
    'erp.naming.var_user': '导出人员',
    'erp.naming.var_date': '导出日期',
    'erp.naming.var_qty': '订单数量',
    'erp.naming.custom_lists': '变量库',
    'erp.naming.no_custom': '库中暂无自定义变量',
    'erp.config.located_row': '指定行',
    'erp.config.logic': '逻辑',
    'erp.config.if': '如果',
    'erp.config.set': '设定',
    'erp.config.quantity': '数量',
    'erp.config.place_order': '下单',
    'erp.toast.order_placed': '订单已下达并导出 BOM',
    'erp.config.bom_arch': 'BOM 架构',
    'erp.toast.system_exported': '系统数据导出成功',
    'erp.fill.options': '自动填充选项',
    'erp.fill.copy': '复制单元格',
    'erp.fill.series': '填充序列',
    'erp.editor.req': '必填',
    'erp.editor.half': '半宽',
    'erp.editor.full': '全宽',
    'erp.editor.label': '字段标签',
    'erp.editor.label_ph': '请输入标签...',
    'erp.editor.var_id': '变量 ID',
    'erp.editor.var_name': '变量名称',
    'erp.editor.var_desc': '逻辑公式中的变量名（仅限字母数字）',
    'erp.editor.save': '保存',
    'erp.editor.width': '宽度',
    'erp.editor.config': '配置',
    'erp.editor.required': '是否必填',
    'erp.editor.placeholder_ph': '占位提示文字...',
    'erp.editor.help_ph': '帮助/提示文字...',
    'erp.editor.show_grid': '在表格中显示',
    'erp.editor.show_batch': '在批量编辑中显示',
    'erp.editor.options': '选项',
    'erp.editor.items': '个选项',
    'erp.editor.option_ph': '选项',
    'erp.editor.add_option': '添加新选项',
    'erp.editor.notice_content_ph': '输入通知内容...',
    'erp.editor.default_content_ph': '输入默认内容...',
    'erp.logic.engine': '逻辑引擎',
    'erp.logic.visibility': '显示规则 (Show ...)',
    'erp.logic.expression_ph': '表达式...',
    'erp.logic.calculation': '计算公式 (=)',
    'erp.logic.formula_ph': '公式...',
    'erp.logic.dynamic_options': '动态选项规则',
    'erp.logic.returns_array': '返回数组',
    'erp.logic.external_data': '外部数据逻辑',
    'erp.logic.simulated_api': '模拟 API',
    'erp.logic.regex_validation': '正则验证',
    'erp.logic.regex_ph': '正则模式...',
    'erp.logic.error_msg': '错误提示',
    'erp.logic.custom_validation': '自定义逻辑验证',
    'erp.logic.readonly_rule': '只读规则',
    'erp.logic.required_rule': '必填规则',
    'erp.logic.disabled_rule': '禁用规则',
    'erp.logic.default_rule': '默认值规则',
    'erp.rule.mapping_tab': '级联映射',
    'erp.rule.logic_tab': '逻辑规则',
    'erp.rule.logic_group': '逻辑条件组',
    'erp.rule.current_row': '当前行',
    'erp.rule.field_ph': '字段...',
    'erp.rule.value_ph': '值...',
    'erp.rule.add_condition': '添加条件',
    'erp.rule.target_field': '目标字段',
    'erp.rule.select_target_ph': '选择生效目标...',
    'erp.rule.set_value': '设定值',
    'erp.rule.set_value_ph': '例如: VIP, 100, {f1} * 2',
    'erp.rule.multi_cascade': '多级联映射',
    'erp.rule.sync_mode': '🔗 同步模式',
    'erp.rule.sync_mode_title': '同步模式: 所有组共享相同的选项值',
    'erp.rule.independent_mode': '🔓 独立模式',
    'erp.rule.independent_mode_title': '独立模式: 每组的选项值独立设置',
    'erp.rule.sync_enabled_msg': '💡 同步模式已启用: 修改任意组的"选项值"将自动同步到其他对应行',
    'erp.rule.cascade_group_num': '级联组',
    'erp.rule.source_field_ph': '监听字段 (Source)...',
    'erp.rule.target_field_ph': '目标字段 (Target)...',
    'erp.rule.source_val_ph': '当值为...',
    'erp.rule.target_val_ph': '设为...',
    'erp.rule.add_mapping_val': '添加映射值',
    'erp.rule.add_cascade_group': '添加级联组',
    'erp.rule.tab_title': '标签标题 (可选)',
    'erp.rule.tab_title_ph': '默认使用说明文字...',
    'erp.rule.save_edit': '保存规则修改',
    'erp.rule.apply_stack': '应用到当前规则栈',
    // AI Import
    'erp.ai.import_title': 'AI 导入',
    'erp.ai.import_desc': '正在根据表格生成表单',
    'erp.ai.progress': '进度',
    'erp.ai.step1': '读取文件',
    'erp.ai.step2': '解析结构',
    'erp.ai.step3': 'AI 分析模式',
    'erp.ai.step4': '生成组件',
    'erp.ai.analyzing': 'AI 正在分析数据模式...',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('gen_pm_language');
      return (saved === 'zh' || saved === 'en') ? saved : 'en';
    }
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('gen_pm_language', lang);
    }
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
